### ISSUE TITLE
Interface Error 999 / NSURLErrorDomain 999 - Crash on iPad

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratchjr#109]
I was going through the steps in https://github.com/LLK/scratchjr/issues/108 to test the various languages. I had been testing in Spanish, then switched to English, then went to the Interface Guide (in the About section). When I clicked on the Interface Guide tab, the app crashed (I was returned to the home screen; the app was closed). I opened the app again, clicked on the Interface Guide tab, and again the app crashed. I took the tablet over to @chrisgarrity's desk and we re-opened the app and went to the Interface Guide tab. This time the app didn't crash, but the page did not load - it displayed an error message, saying something like "Interface Error 999" (unfortunately we didn't take a picture and could not repro it after that).

From some googling, @chrisgarrity and I were thinking it could have been this error: http://stackoverflow.com/questions/1024748/how-do-i-fix-nsurlerrordomain-error-999-in-iphone-3-0-os

When you click around a lot on the app, e.g. if you switch quickly between tabs in About and click various number tags/ labels in the diagrams, you will see various states as the pages load, e.g. the labels displayed vertically along the left side of the page and the diagram below them, or the block images displayed vertically along the left side of the page.

When you change languages, the first load of the new language is not particularly fast (it's a lot of information). It could be that by loading the various languages in succession and clicking across the app quickly, this error was triggered.

**Comment by chrisgarrity** [comment]
closing stale issue
