### ISSUE TITLE
Add support for shared Android tablets/chromebooks for education

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#117]
Similar to adding support for shared iPads for education.

It looks like we should be using Android Backup to backup app files to the users Google Drive: https://developer.android.com/guide/topics/data/backup.html

**Comment by chrisgarrity** [comment]
@judeebene it would be great to get some help fixing bugs for ScratchJr. Hopefully there is enough information for you to get started in the README. 

One bug that would be helpful to look at is #14. While the case specifically mentions dropbox, I think there are issues with opening scratchjr projects on any shared drive (e.g. Google drive). It would be great to get documentation in the issue of all the places it fails (or doesn't fail). Then if you wanted to try to fix it, that would be a great help.

Thanks for your help!

**Comment by matiasdelellis** [comment]
Sorry to ask in this issue.
Where do store scratch projects?. Any way to access them and copy them to a computer from usb?

Thanks..

**Comment by chrisgarrity** [comment]
Projects are stored internally to ScratchJr in a database, not as individual project files. They are not accessible via USB. You can use the 'Share by email' feature which generates a project file from the internal data.

**Comment by rkuo** [comment]
I have the same problem. It worked once, then it would not open sjr file anymore.
I did a little research, don't know this will help or not?
In Setting >> Apps: ScratchJr is on the list.
In Setting >> Apps >> Default Apps >> Set As Default: ScratchJr is **not** on the list.

When I click the attached project, ScratchJr is not in the suggested App list.
I use a Samsung Tablet S3 SM-T820, Android v8.0.0, ScratchJr v1.2.6 .

**Comment by mrscanning** [comment]
Hello!
I posted this in another spot, too.  We are trying to use Scratchjr app on our school district chromebooks to teach a Project Lead the Way module.

Right now the app opens, but it is just stuck on the Home, School, Other page.  Is there any way to get past this?

Here is the chromebook info.  They are new this year!

HP Chromebook 11A G6 EE
 
Product ID# 6kj19UT#ABA

Please help!
canningj@casdschools.org

**Comment by deepankarmalhan** [comment]
Product backlog

**Comment by deepankarmalhan** [comment]
JR-252
