### ISSUE TITLE
24 bit sounds broken on some Android tablets

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#118]
24 bit encoded wav sounds are not supported on some versions of Android. It seems to be an issue on most CyanogenMod versions, and certain tablets (Sony Xperia Z2). 
https://developer.android.com/guide/appendix/media-formats.html

Here's a video of what happens:
https://www.dropbox.com/s/fc379w2586qd2i0/scratchjr-broken-wav.mp4?dl=0

Should we convert wav sounds to 16-bit for all versions?

QA:
- [ ] sound effects sound ok (pop, dragging a block, opening a project, drawing in the editor, remove a block etc.)

**Comment by thisandagain** [comment]
Seems like 24-bit audio is probably excessive in any case and downsampling would reduce the size of the APK.

**Comment by jwzimmer** [comment]
QA-OK, tested as part of https://github.com/LLK/scratchjr/issues/119#issuecomment-288766639.
