### ISSUE TITLE
Recorded sounds don't play in ScratchJr on iOS 10.2

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#119]
We've had a couple of reports from people who recently updated to iOS 10.2 that playing recorded sound doesn't work. They can record sound, and playing the sound back in the recorder works, but the sound doesn't play when using the sound block in the program.

**Comment by chrisgarrity** [comment]
I emailed a message with an example of a project with the missing sounds to the LLK ipad email. I didn't attach it here to make sure we're not inadvertently sharing a user's personal data.

**Comment by chrisgarrity** [comment]
Kaitlyn (Tufts) upgraded an iPad to 10.2 and confirms the problem:
I just updated an iPad to 10.2 and the sound blocks are definitely a problem. Any sound block (recorded or Pop) does not play in a program sequence, and the program stalls once it reaches the sound block. It also stalls when you drag down the sound block and tap it on its own. When you record your voice, you can play it back fine (so I don't think it's a microphone/speaker issue), but once you hit the "check" button it will not play in the program. If you have a second program running with Start on Green Flag that has anything but a sound block, that will run even when the first program is stalled from the sound block.

**Comment by thisandagain** [comment]
Update: I'm not able to replicate on the latest build from `develop`.

**Comment by thisandagain** [comment]
@chrisgarrity Could we do an install to your tablet and give it another try?

**Comment by chrisgarrity** [comment]
Update: Able to replicate on an iPad 4 model (McMuffin). Appears to be an issue with webaudio that only hits older iPads. We probably need to replace webaudio with native audio on iOS. Essentially we need to create an iOS equivalent of the Android sound library: https://github.com/LLK/scratchjr/blob/master/android/ScratchJr/app/src/main/java/org/scratchjr/android/SoundManager.java

**Comment by jwzimmer** [comment]
@chrisgarrity, do you want to discuss the testing for this on Monday?

I was thinking more or less:
- Find 2 (if possible) older/ affected iPads, a newer/ unaffected iPad, and an Android tablet
- Try the following test cases:
  - [ ] Any sound block (recorded or Pop) should play in a program sequence
    - [ ] The program should not stalls once it reaches the sound block
  - [ ] The program should not stall when you drag down the sound block and tap it on its own
  - [ ] When you record your voice, you should be able to play it; once you hit the "check" button it should play in the program
  - [ ] After downloading & reopening a project with sounds, the sounds should still work
  - [ ] An older pre-fix project's sounds should still work

I wasn't sure I understood what this meant:
> If you have a second program running with Start on Green Flag that has anything but a sound block, that will run even when the first program is stalled from the sound block.

**Comment by eivindeklund** [comment]
I am seeing what sounds like it may be the same problem on Android, on a Pixel C tablet running Android 7.1.1 and Scratch Jr 1.2.3.

The symptoms are almost the same:
* The sounds do not play in the program sequence
* The program stalls once it reaches the sound block
* When recording I cannot replay the sounds [this sounds like it is different from the above]

**Comment by chrisgarrity** [comment]
@eivindeklund It's unlikely that this is the same issue since sounds are in native Android/iOS code. We're opening a new bug to track this android issue #118

**Comment by jwzimmer** [comment]
### Testing

- Find 2 (if possible) older/ affected iPads, a newer/ unaffected iPad, and an Android tablet
  - [x] McMuffin iPad
    - Did demonstrate bug before upgrading Scratch Jr

---
**McMuffin**, iPad, using Test Flight > Scratch Jr beta
- Try the following test cases:
  - [x] Any sound block (recorded or Pop) should play in a program sequence
    - [x] The program should not stalls once it reaches the sound block
  - [ ] The program should not stall when you drag down the sound block and tap it on its own
  - [ ] When you record your voice, you should be able to play it; once you hit the "check" button it should play in the program
  - [ ] After downloading & reopening a project with sounds, the sounds should still work
  - [ ] An older pre-fix project's sounds should still work
  - [x] Sounds in the sample projects should work
  - [ ] Choose some items from [smoketesting](https://github.com/LLK/scratchjr/wiki/Smoke-Testing-Test-Cases)
    - [x] About page
    - [ ] Existing project
    - [x] Sample projects

---
- Try the following test cases:
  - [ ] Any sound block (recorded or Pop) should play in a program sequence
    - [ ] The program should not stalls once it reaches the sound block
  - [ ] The program should not stall when you drag down the sound block and tap it on its own
  - [ ] When you record your voice, you should be able to play it; once you hit the "check" button it should play in the program
  - [ ] After downloading & reopening a project with sounds, the sounds should still work
  - [ ] An older pre-fix project's sounds should still work
  - [ ] Sounds in the sample projects should work
  - [ ] Choose some items from [smoketesting](https://github.com/LLK/scratchjr/wiki/Smoke-Testing-Test-Cases)
    - [ ] About page
    - [ ] Existing project
    - [ ] Sample projects
