### ISSUE TITLE
Sounds not playing, program stalls at sound block, recorded sounds can't replay - Android

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratchjr#124]
Reported by @eivindeklund in https://github.com/LLK/scratchjr/issues/119#issuecomment-287527336:

> I am seeing what sounds like it may be the same problem on Android, on a Pixel C tablet running Android 7.1.1 and Scratch Jr 1.2.3.

> The symptoms are almost the same:
* The sounds do not play in the program sequence
* The program stalls once it reaches the sound block
* When recording I cannot replay the sounds [this sounds like it is different from the above]

**Comment by chrisgarrity** [comment]
@eivindeklund We have not been able to reproduce this on a Nexus 9 running Android 7.1.1. We're getting a Pixel C to have one in our test suite. In the meantime, could you check that ScratchJr has permission to use the microphone in your settings. Thanks.

**Comment by chrisgarrity** [comment]
@eivindeklund We still have not been able to reproduce this issue on the new Pixel X running Android 7.1.1. We have ScratchJr 1.2.4 installed (the latest version). Could you check whether you have the same issue after updating to the newest version.

**Comment by chrisgarrity** [comment]
closing stale issue, can reopen if reproduced.
