### ISSUE TITLE
Paint editor calibration not working on some tablets

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#137]
On android there is an interaction between the paint-editor zoom level, and the pixel density of the device. On high pixel density device, the element being drawn does not line up with the touchpoint when the editor is zoomed. At no zoom, everything is fine. This has led to a lot of thrashing on this issue. Taking out the zoom-level calculation ended up "fixing" the problem on some devices (probably because the default zoom level and the pixel density matched up), but caused the calibration problem to move to other devices.

In the paint editor the element being drawn is offset from the location of your finger.  It's up to the left. It has been reported several times, often on Samsung devices, but we haven't seen it on any of our devices. 
![out.gif](https://codetreeusercontent.s3.amazonaws.com/uploads/f3f422f6-a9f6-4a72-91f7-ca9fe6dcfc0b/out.gif)

Reported on 
Samsung Tab A: T580 running Android 7.0 (1200 x 1920 pixels (~224 ppi pixel density))
Samsung Tab A: SM-P580 with S Pen, Android version 6.0.1 (1200 x 1920 pixels (~224 ppi pixel density)
Galaxy Tab S2, Android 5.0.2 (1536 x 2048 pixels (~320 ppi pixel density))
ASUS ZenPad 3s 10 (Z500M), Android 6.0.1 (1536 x 2048 pixels (~264 ppi pixel density))

**Comment by fortuik** [comment]
Same behavior on
Lenovo TAB2 A10-30 (TB2-X30F), Android 6.0.1, 1280x800

**Comment by chrisgarrity** [comment]
@fortuik Thanks for the info, every data point helps.

**Comment by chrisgarrity** [comment]
Potential workaround from a user:

> Here's an update on the problem. If I pinch in on the screen suddenly it is calibrated correctly and I can draw where my finger is.

**Comment by chrisgarrity** [comment]
Same behavior on Pixel C, 2560 x 1800 (~308)

**Comment by fortuik** [comment]
I can confirm that zooming out at maximum allows for correct painting, zoom in breaks it.

**Comment by Raincloud7** [comment]
Same issue here with an old Nexus 10. Depending on the zoom level the offset is larger or smaller. Unfortunately the paint tool is not usable like this.

**Comment by ryanwarsaw** [comment]
If this is still open after the 30th I'll happily take this issue and file a PR for it, I've got a hunch as to why this might be happening but need to dig further in order to articulate it properly.

**Comment by chrisgarrity** [comment]
@ryanwarsaw it's definitely a problem with the scaling calculation. The offset gets bigger the further you are from the top left (0,0) point. I'm probably not going to get to it before Oct 30th unless other things go faster than expected. Let us know if you do start looking into it.

**Comment by ryanwarsaw** [comment]
Diving into this in the next couple of days, anything I should be aware of?

**Comment by chrisgarrity** [comment]
@ryanwarsaw One thing to be aware of is the unfortunately named https://github.com/LLK/scratchjr/blob/develop/src/iPad/iOS.js

The name is a relic from the time before ScratchJr was ported to Android and only ran on iPads. The src/iPad directory has files that handle the interface between javascript and the native tablet.

Since the calibration is only an issue on Android, it may only need changes in the native java code, but I thought I'd still point out this as it can be very confusing.

**Comment by Murkantilism** [comment]
Confirming reproduction of this issue across 18 units of the Samsung Galaxy Tab A 8.0 (Model SM-T350)

The pinch out to zoom workaround works and as /u/fortuik said, zooming back in reproduces the issue.

Been poking through Paint.js and Events.js searching for suspects, may open PR if I find something!

**Comment by ryanwarsaw** [comment]
Hi quick update, it took me a while to Scratch JR to run, I was having issues with running the scripts in the `/bin` folder, I've figured it out though and its working now. I dove into trying to replicate the problem, and tried with emulated versions of all the devices here.

I wasn't able to replicate the issue, it seems to work as intended for me. I attempted using a few different versions of Android, to no resolve. There is certainly an issue here though, it's just a matter of being able to replicate it. 

I'm going to try using this tool I found (http://tools.android.com/tips/hardware-emulation) tomorrow, so I can control the emulator with a physical touch event and see if maybe the emulator is treating things differently than an actual device, unfortunately that's all I can think of.

I tried to view that gif you posted of the bug in action, but it appears to be a dead link. I also couldn't replicate it on my Nexus 5X as my only physical Android device currently.

**Comment by chrisgarrity** [comment]
@ryanwarsaw thanks for the update - is there something we should document about the scripts in the `/bin` folder to help others? Here's the gif again. If it still doesn't show up here's the [link on dropbox](https://www.dropbox.com/s/ghtvg3qf3q2vw27/calibration-bug.gif?dl=0)

![calibration-bug](https://user-images.githubusercontent.com/399209/33073931-623cd712-ce92-11e7-9fcc-c6dc6671e4f4.gif)

Yes, it's definitely hardware related as it only seems to happen on some Android devices.

**Comment by ryanwarsaw** [comment]
@chrisgarrity The webpack one assumes path to node, for me as an `nvm` user it's located in a totally different place. The python one I'm not sure, it would error the first time then run without error every time after that, maybe a race condition between directory creation and work?

I tried the hardware emulation tool, unfortunately it looks like they got rid of it a few versions ago when they implemented multi-touch gestures for the emulator. I'm not really sure what to do at this point, I don't have any of the devices listed above so unfortunately I don't think I can do anything.

**Comment by chrisgarrity** [comment]
@ryanwarsaw good to know about the nvm problem as that will probably be an issue for more people. Are you on Windows or OSX? We don't have many developers on Windows, so we tend to miss those problems.

Thanks for taking a look at this - I agree, there's not much you can do if you don't have a device that exhibits the problem.

**Comment by ryanwarsaw** [comment]
@chrisgarrity macOS, ideal solution would be to just use PATH defined `node`. I'm not sure if it's even possible to run scratch jr on Windows currently, maybe inside a sandboxed ubuntu environment or something.

**Comment by Raincloud7** [comment]
Hi! This problem was bugging us so much that I spent some time on it to fix it. It is a problem in the translation of screen to svg coordinates. By removing these lines 

`globalPoint.x = globalPoint.x / Paint.currentZoom;
globalPoint.y = globalPoint.y / Paint.currentZoom;`

from PaintAction.js (1134) I could fix the issue on my device (Nexus 10). Let me know if I can do anything to get this bugfix in the official version. 

greets Andreas

**Comment by nomnomnomyes** [comment]
@Raincloud7 i don't understand how to do that, may i have the edited version of scratch for android?

**Comment by Raincloud7** [comment]
@nomnomnomyes i was hoping to help fixing this in the official version. To do it yourself you would have to setup the development environment which takes some time and knoledge. I am still hoping for a fix from the devs.

**Comment by liyashuang** [comment]
@ryanwarsaw “Hi quick update, it took me a while to Scratch JR to run, I was having issues with running the scripts in the /bin folder, I've figured it out though and its working now” 
How do you solve this problem？

**Comment by ryanwarsaw** [comment]
I think the problems I was dealing with were because the project was using an absolute path to node (/some/etc/node) when it was else where because I was using NVM.

**Comment by liyashuang** [comment]
@ryanwarsaw @chrisgarrity 
Now I am running the Android project under the windows environment. I have reported the following mistake. Can anyone provide a solution?![](https://github.com/liyashuang/3dturn/raw/master/img/3.jpg)

**Comment by chrisgarrity** [comment]
@liyashuang I'm not sure that it's possible to build ScratchJr on windows currently. It would be great to hear if anyone has managed it.

**Comment by chrisgarrity** [comment]
Reopening this issue - it appears to be an interaction between zoom level and the pixel density of the android device.

**Comment by chrisgarrity** [comment]
Fixed in https://github.com/LLK/scratchjr/pull/234
