### ISSUE TITLE
Shared projects on dropbox won't open

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#14]
_From @chrisgarrity on February 11, 2016 19:21_

Sjr projects on Dropbox open in ScratchJr on iOS, but don't open on android - it doesn't know which app to use.
Google drive links also open on iOS - not tested on Android yet.

_Copied from original issue: LLK/scratchjr-private#480_

**Comment by deepankarmalhan** [comment]
Closing for #489
