### ISSUE TITLE
Add usage survey splash screen

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#141]
We want to add a page that asks for usage information the first time ScratchJr is opened on a device.

The questions is:
How are you using ScratchJr?
The choices are:
* Home
* School
* Other
with an option to not respond 'Don't ask again'

Here's the prototype:
![IMG_0119.PNG](https://codetreeusercontent.s3.amazonaws.com/uploads/259627a6-68a0-4fc9-9f22-933628ad85e5/IMG_0119.PNG)

We need to confirm the design for the page, and get icons.

**Comment by carljbowman** [comment]
I tried to use styling that was already built into the ScratchJr splash screens. Here are two versions:

#### Version 1 - Depending on the flexibility of the splash screen code, we can reuse a bunch of the styling
![tablet landscape v1](https://user-images.githubusercontent.com/3409578/28875538-deb3c322-7763-11e7-970a-f2095fe8ccbf.png)

#### Version 2 - If the code is not super flexible, here is an alternative version
![tablet landscape v2](https://user-images.githubusercontent.com/3409578/28875573-fa2a17d2-7763-11e7-8872-15a5a5bdf3d1.png)

[icons.zip](https://github.com/LLK/scratchjr/files/1193968/icons.zip)
