### ISSUE TITLE
Does scratchjr Android not support compiling under Windows?

### ISSUE THREAD

**Issue by zz5221** [LLK/scratchjr#146]
I tried to compile scratchjr Android under windows, but it was unsuccessful. The AndroidStudio prompt"Error:Execution failed for task ':app:generateWebpackBundle'.
> A problem occurred starting process 'command './bundle-compile.sh'"

**Comment by ryanwarsaw** [comment]
I don't believe Windows 10 (or lower) allows you to run Bash scripts unless you're using Bash for Ubuntu on Windows 10, or something like that. So I'd say your assessment is likely correct. I'm not sure if there are any other blocks to getting it to run on Windows, but that specific file could use some TLC. It assumes path to Node, and could probably be replaced with a more universal solution given the simplicity of script itself.

**Comment by thisandagain** [comment]
Hi @zz5221. As @ryanwarsaw noted the `bundle-compile.sh` bash script was not designed to work with Windows. You may be able to get it working with WSL but we have not attempted to do so yet.

**Comment by thisandagain** [comment]
Sidenote: great to see you @ryanwarsaw!

![](https://media2.giphy.com/media/mW05nwEyXLP0Y/giphy.gif)

**Comment by ryanwarsaw** [comment]
@thisandagain 👋  I'd love to contribute to some of the bugs once time permits, for now i'm just a lurker 👀  hope you're doing great!

**Comment by zz5221** [comment]
Thank you for your reply and I'm a novice at scratchjr.I am trying to learn English now,

Thank you very much for your reply @ryanwarsaw @thisandagain

**Comment by ryanwarsaw** [comment]
I couldn’t even tell that English isn’t your primary language, you speak it very well!

**Comment by sugar-tong** [comment]
> Hi @zz5221. As @ryanwarsaw noted the `bundle-compile.sh` bash script was not designed to work with Windows. You may be able to get it working with WSL but we have not attempted to do so yet.

I tried to compile scratchjr Android under ubuntu, but it was unsuccessful. The AndroidStudio prompt"Error:Execution failed for task ':app:generateWebpackBundle'.

**Comment by ryanwarsaw** [comment]
@sugar-tong If I had to guess, it's likely to do with the node.js path situation. See where it is installed on your system, and if it's different than in the script modifying that should resolve the situation.
