### ISSUE TITLE
Revise language selection menu

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#147]
The current design for selecting language (page of language buttons) is ok for the current number of languages, and can be squeezed (add a third column) for a few additional languages. However, if the list of languages gets really long it's going to get hard to use. 

The app has been translated into several more languages, but there is no more room on the settings page.  If we make the page scrollable we can fit more languages.

There are 27 languages that could potentially be listed (>96% translated), but we have a full page with 16 languages.

**Comment by rkuo** [comment]
There are 12 language options in the default installation. How to add or replace one in the list with a different language? Do I need to re-build the apps? Is there a procedure I can follow?

**Comment by chrisgarrity** [comment]
@rkuo [Transifex](https://www.transifex.com/llk/scratchjr/) is our translation platform for ScratchJr, when a language has been fully translated and reviewed it can be considered for inclusion in the App the next time the App is released. If you want to try building a version with a different language, you'll need to provide the right files in https://github.com/LLK/scratchjr/tree/develop/editions/free/src/localizations
and set the language in https://github.com/LLK/scratchjr/blob/develop/editions/free/src/settings.json

However, we will not accept pull requests for new languages as that would circumvent our normal process.

**Comment by rkuo** [comment]
Thank you very much for quick response. 

I followed the two links you gave to me. It was a good news the one I am interested in zh-TW is already included in both places. I assume the new build is already exist. It may be the new build has not been uploaded to play.google.com site yet. Also, I do not have my computer setup to build the app, it may take some struggle per my skill level. If my assumption is correct, can you (or someone) push the updated version to Play.google.com. That will be really nice. I am in the process of writing some tutorial for young kids in Taiwan. It will more effective they have proper screen shoots. 

I usually see many software referring two different Chinese languages as  Chinese(Simplified) or Chinese(Traditional), other than Chinese(China) and Chinese(Taiwan). Will the former approach be more political neutral? Just a curiosity question, not relate to my original request, please ignore, if this creates some complexity/delay.

Have a happy new Chinese New Year!!

Richard

**Comment by chrisgarrity** [comment]
We made languages scrollable. Perhaps not ideal, but we can reopen design issue when there is time to work on it.
