### ISSUE TITLE
pysvg install  failure

### ISSUE THREAD

**Issue by chenweigh** [LLK/scratchjr#163]
sudo easy_install pysvg
this is the issue:

Searching for pysvg
Reading https://pypi.python.org/simple/pysvg/
Download error on https://pypi.python.org/simple/pysvg/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
Couldn't find index page for 'pysvg' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
No local packages or working download links found for pysvg
error: Could not find suitable distribution for Requirement.parse('pysvg')

How to fix it?

**Comment by thisandagain** [comment]
Sorry @chenweigh but we do not provide support for Python, PIP, or `easy_install`. You'll need to consult with those communities / forums.
