### ISSUE TITLE
Suggestion: Scratch Jr. to be packaged for F-Droid.org Repository

### ISSUE THREAD

**Issue by cathalgarvey** [LLK/scratchjr#165]
Hi folks,

I've also opened this over on [F-Droid's Packaging Suggestions Repo](https://gitlab.com/fdroid/rfp/issues/553) so please see-also over there.

The brief version is that Scratch Jr. is an incredible thing and I'm glad my kids have been able to use it.. but the less I indoctrinate them into accepting proprietary spyware (that is, Google Play etc.), the better. It'd be great if I could stock their devices with inspirational apps like this using a more respectful outlet, like F-Droid.org and their repository of Free/Libre apps.

Thanks! :)

**Comment by thisandagain** [comment]
Thanks for the suggestion @cathalgarvey! We'll take a look. :-)

**Comment by chrisgarrity** [comment]
@cathalgarvey it looks like ScratchJr would run afoul of the F-Droid rule against 3rd-party libraries like Google Analytics which we do use.

**Comment by cathalgarvey** [comment]
Is it not possible to add a compile-flag to remove tracking, to facilitate ethical packaging?

On 16 April 2018 18:13:54 GMT+01:00, chrisgarrity <notifications@github.com> wrote:
>@cathalgarvey it looks like ScratchJr would run afoul of the F-Droid
>rule against 3rd-party libraries like Google Analytics which we do use.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/LLK/scratchjr/issues/165#issuecomment-381679325

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Poussinou** [comment]
@cathalgarvey You can write a new build flavor in your gradle (doc [here](https://developer.android.com/studio/build/build-variants)) to remove google analytics and other proprietary stuff like that for the F-Droid build.

**Comment by IzzySoft** [comment]
So any news on this? The request for packaging at F-Droid is stalled, waiting for this issue to be solved (together with the linked one).

**Comment by cathalgarvey** [comment]
I'd still love to see this happen. Especially now that Scratch no longer requires Adobe-anything to run, the whole ecosystem is something I'm happier to push kids towards, and the Scratch Jr. app has been really instrumental to my efforts so far.

**Comment by cathalgarvey** [comment]
From [over at Gitlab](https://gitlab.com/fdroid/rfp/issues/553#note_134917982) we have the following checklist for moving this forward:

* Agreement or tacit support from the ScratchJr maintainers to get this on Gitlab, including agreement about removing surveillance libraries.
* Some way to facilitate releases on F-Droid, ideally tagged releases.
* "Some" upstream assistance in making it easier to remove surveillance. I'm not au fait here, but it sounds like this would involve an alternative gradle build?
* Someone committed to maintaining the mechanism for removing surveillance. My impression is that this could be either the maintainers committing to keep/test an alternative build, or a downstream community member maintaining a patchset over at the F-Droid project.

**Comment by ryanwarsaw** [comment]
Do the libraries need to be entirely removed, or can they simply be disabled (see: https://developers.google.com/analytics/devguides/collection/android/v4/advanced).

**Comment by Rudloff** [comment]
They have to be removed entirely from the build.
The cleanest way to do this is usually a [build variant](https://developer.android.com/studio/build/build-variants).

**Comment by IzzySoft** [comment]
Any progress on this? Issue here seems to have gone stale. And at F-Droid we cannot proceed before the dependency on GMS is out of the way. Do we still pursue that?

**Comment by cathalgarvey** [comment]
I would still *love* to see Scratch Jr. being made available to kids who don't have Google on their shoulders, either for rights or for simple economics reasons.

Lotta kids out there right now who probably can't afford a Google-infested phone, who could really do with some Scratch. ;)

On 25 July 2019 12:51:34 GMT+01:00, Izzy <notifications@github.com> wrote:
>Any progress on this? Issue here seems to have gone stale. And at
>F-Droid we cannot proceed before the dependency on GMS is out of the
>way. Do we still pursue that?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/LLK/scratchjr/issues/165#issuecomment-515013393

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by chrisgarrity** [comment]
In order to keep Scratch and ScratchJr free the Scratch Foundation relies on donations. Donors like to know that their donations are having an impact. One of the ways we show that is by collecting de-identified usage data so we can answer questions like how many users, how many sessions.

**Comment by cathalgarvey** [comment]
That's your prerogative and all, but Google Analytics is not "de-identified", it's "abusively invasive ad company analytics" and forms just part of a surveillance engine that is already profiling kids on their browsers, at school, as they move and talk and interact at home and elsewhere. The fact that the Scratch Foundation chooses to aggregate and "de-identify" some of this data is nice and all, but a malignant corporation is getting hyper-personalised data on kids and adults using Scratch anyway.

Pity, but OK. I'm not in a position to fork and provision a more privacy-respectful alternative, but I'll hope someone does, someday. If they do, it would be nice to see it on F-Droid or with straight APKs, for parents who want to keep their kids' privacy intact.

**Comment by IzzySoft** [comment]
If you just want those numbers, use a self-hosted analytics solution like Matomo. If enabled by default this would "earn" you the `Tracking` AntiFeature but make your app acceptable to F-Droid. But knowing my donations cause you using Google Analytics for justification would keep me from donating (my personal stance, YMMV).

**Comment by yashpalgoyal1304** [comment]
so, this decision is final @chrisgarrity right??

**Comment by yashpalgoyal1304** [comment]
well yeah, seems understandable. hey, "OKAY GOOGLE". 

* MIT's appinventor, and MIT's scratch both ~~are based off of~~ have some relation with google blockly. 
* Google blocked access to appinventor by restricting it behind "google account login" and
* it injected its services in Scratch

It's perfectly understandable and should be conclusive as well.

**Comment by yashpalgoyal1304** [comment]
@yashpalgoyal1304 well yeah, seems understandable. hey, "OKAY GOOGLE".

MIT's appinventor, and MIT's scratch both are based off of have some relation with google blockly.
Google blocked access to appinventor by restricting it behind "google account login" and
it injected its services in Scratch
It's perfectly understandable and should be conclusive as well.
