### ISSUE TITLE
How to make characters and pages on app default installation optional ？

### ISSUE THREAD

**Issue by brucebnu** [LLK/scratchjr#166]
hi,
Question 1
I want to design and add default characters and pages in the app.
SVG I can design, but how do I add it?
Note that it is the default addition of the release APP.
and also how to make Sample projects then add the release APP.

yes：）， **characters，pages，sample projects**
Where can I find character and pages,sample projects of official that I can use at offline kindergarten?

Question 2
The default picture is not loaded, how do I debug in Xcode environment.
Is there any good debugging advice and skills?
<img width="705" alt="20b2f78b-c824-4488-b7c0-6a2e84ae34ce" src="https://user-images.githubusercontent.com/2786096/38886851-c6abbdae-42a9-11e8-9e31-ab741ce27f2c.png">

thank you so much. Smart guy！：）

**Comment by chrisgarrity** [comment]
Sorry for the delay in answering these questions, but I'll put them here in case they're helpful for anyone else in the future.
1. For copyright reasons, the media from the official ScratchJr is not available publicly. There are two samples: a character (star) and a background (farm). You can add your own media by adding them to the `editions/free/src/svglibrary` folder, and updating the details in  `editions/free/src/media.json`. Use the sample items as examples.
2. The ScratchJr UI is in a webview. The easiest way to debug is to use Safari (with Developer tools enabled) to connect to the simulator or iPad (in the Develop menu)
