### ISSUE TITLE
Scrachjr on appstore is not similar to the demo. so why? how to get it as that on appstore?

### ISSUE THREAD

**Issue by chenweigh** [LLK/scratchjr#167]
the demo photo:
![img_0786](https://user-images.githubusercontent.com/15101298/38920790-b9589582-4326-11e8-8e64-cd392a419043.PNG)

the appstore photo:
![img_0787](https://user-images.githubusercontent.com/15101298/38920820-c4536534-4326-11e8-82af-002847bc2c26.PNG)

what is wrong?

**Comment by thisandagain** [comment]
As per the terms of our open source license, the core application of ScratchJr is open source, but our name (Scratch and ScratchJr), branding, and other visual assets are proprietary and not available for reuse.
