### ISSUE TITLE
Camera doesn't save image on some Amazon tablets

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#168]
Steps to reproduce:
- In paint editor, click camera button, then touch a shape to fill... shape shows live video as fill
- touch the camera to take the photo
- filled shape turns green

Only seems to be an issue on Amazon Fire tablets. May also be related to a FireOS update - ones with the issue are running FireOS 5.6

Fire HD 8 (2017)
Fire (2015)
Kindle Fire HD (2013)

Could it be related to using `android.hardware.camera` instead of `android.hardware.camera2`?

**Comment by do1eh** [comment]
Issue also in fire7
