### ISSUE TITLE
Could not get unknown property 'prepareFreeDebugDependencies'

### ISSUE THREAD

**Issue by stormzy** [LLK/scratchjr#174]
When I use Android Studio in windows x64 to make this project, i got this error: "Gradle sync failed: Could not get unknown property 'prepareFreeDebugDependencies' for project ':app' of type org.gradle.api.Project".
And I search this in google,but gain nothing.

**Comment by wangjianxiandev** [comment]
I also have the same question

**Comment by chrisgarrity** [comment]
@stormzy @wangjianxiandev I'm assuming you're both on windows. For various reasons the ScratchJr build scripts rely on certain directories having symbolic links to other directories. Windows doesn't handle symlinks, so we've never been able to build ScratchJr on windows. You could try installing the Windows subsystem for Linux and see if that helps. It would definitely be great if someone could figure out a way to build ScratchJr on windows.

**Comment by jedlee6** [comment]
@chrisgarrity But I opened this project in Ubuntu. Android Studio told me the same bugs. How to solve it in Ubuntu?

**Comment by chrisgarrity** [comment]
@jedlee6 unfortunately I don't know what to say. We exclusively build ScratchJr on macOS as it's required for the iOS version. It builds on Android Studio 2.3 on macOS. If you're building on a different OS, or with a different version of Android Studio etc. you'll need to debug the build scripts.

**Comment by jedlee6** [comment]
@chrisgarrity Thank you for replying me! I have figured out how to build the ScratchJr project manually in Windows10 2 days ago. I sincerely appreciate your reply, which motivates me a lot!

**Comment by chrisgarrity** [comment]
@jedlee6 - could you reply with the steps you needed to take to get it to build on Windows10? It would help others who are also on Windows. Thanks!!

**Comment by mcerezuela** [comment]
> @jedlee6 unfortunately I don't know what to say. We exclusively build ScratchJr on macOS as it's required for the iOS version. It builds on Android Studio 2.3 on macOS. If you're building on a different OS, or with a different version of Android Studio etc. you'll need to debug the build scripts.

I have the same Issue on iOS

**Comment by murasu** [comment]
> @chrisgarrity Thank you for replying me! I have figured out how to build the ScratchJr project manually in Windows10 2 days ago. I sincerely appreciate your reply, which motivates me a lot!

I'm getting the same issue when building on Android Studio 3.4 on macOS 10.14.4. @jedlee6 Perhaps the issue may be the same as you had on Windows. Could you please share what was that you changed to get the build going? Thank you.

**Comment by adkevinchang** [comment]
我也有相同的问题。一直没解决。已经使用mac os的环境。  window10也不行。
