### ISSUE TITLE
Move build out of src folder

### ISSUE THREAD

**Issue by yueyuzhao** [LLK/scratchjr#184]
I think build in src folder is not a good practice. When searching in src folder, a lot of build results come out. So why not move it out?

**Comment by chrisgarrity** [comment]
The open source ScratchJr is part of a larger build system that allows us to build multiple versions of the app (e.g., ScratchJr, PBS Kids ScratchJr etc). We have to keep that part private as we do not have permission to make the media assets public (e.g. PBS Kids characters). While I agree that having the build in the src folder is not good practice, changing this now would require additional changes in the other build system, and this is not something that we want to do right now.

**Comment by yueyuzhao** [comment]
Thanks for your explanation.
