### ISSUE TITLE
Edit & play projects in browsers

### ISSUE THREAD

**Issue by yueyuzhao** [LLK/scratchjr#186]
To do this we need:
1. Setup a server to host assets and projects
2. Replace database query in projects
3. Support both touch events and mouse events
4. Implements tablet interface for browsers

**Comment by yueyuzhao** [comment]
5. Import and export project in .sjr format

**Comment by yueyuzhao** [comment]
With more than 10 days heavy development, I setup a server and here is a demo: https://scratchjr.drmer.net/project_1_play.html 
I transfer all JavaScript codes to typescript, which made development much much easier.
Here is the repo: https://github.com/jndrm/scratchjr with following features: 
- [x] Full project editing
- [x] Audio recording
- [x] Take image from camera
- [x] Switch camera if user's computer has multiple cameras
- [x] Clone other user's project
- [x] Export/Download .jsr file
- [x] Import .jsr file

**Comment by yueyuzhao** [comment]
Well, since there is not any response for a long time, I'm going to shut the server down. If any one want to see the result, I'll reopen the server for you. Please don't hesitate to contact me!

**Comment by jedlee6** [comment]
Hi, I'm a new developer in this project. Our team planned to customize this project, but we don't know how to start it. Could you give me some tips. We sincerely appreciate it!
你好！我是大连理工大学的一名大三学生呢，我们团队想要根据这个开源项目定制出自己的项目，但不知道这个项目用了什么框架，也不知道从什么地方开始呢，能请学长赐教一下吗？如果学长能够帮助我们，真心十分感谢学长！~

**Comment by yueyuzhao** [comment]
Hi @jedlee6 , if you have any question, please open an issue for discussion.
