### ISSUE TITLE
Proposal: transfer javascript to typescript

### ISSUE THREAD

**Issue by yueyuzhao** [LLK/scratchjr#191]
Hi there,
    This is a project that makes our children's life much more wonderful and make it easy to explore the magic programming world. I love this project very much and have a great willingness to help to make this project better and I'm trying to do so. 
> TypeScript is an open-source programming language developed and maintained by Microsoft. It is a strict syntactical superset of JavaScript, and adds optional static typing to the language. TypeScript is designed for development of large applications and transcompiles to JavaScript. 

Transfering JavaScript to TypeScript makes development much more easier, and helps to find bugs while compiling.

**Comment by chrisgarrity** [comment]
@yueyuzhao ScratchJr is maintained by the same developers as Scratch (e.g. https://github.com/LLK/scratch-gui), and we're trying (over time) to bring the ScratchJr development closer to the other projects. We're not using typescript in any of the other projects, so using it in ScratchJr would be contrary to that effort.

**Comment by yueyuzhao** [comment]
Alright, thanks for your explanation.
