### ISSUE TITLE
xcode build app.bundle.js and app.bundle.js.map not found file

### ISSUE THREAD

**Issue by leejuen** [LLK/scratchjr#194]
building file list ... rsync: link_stat "/Users/lijun/Downloads/scratchjr-develop/ios/../editions/free/src/app.bundle.js" failed: No such file or directory (2)
rsync: link_stat "/Users/lijun/Downloads/scratchjr-develop/ios/../editions/free/src/app.bundle.js.map" failed: No such file or directory (2)
done

**Comment by yueyuzhao** [comment]
It seems that you didn't build these files. Please refer to : https://github.com/LLK/scratchjr#building-scratchjr

**Comment by leejuen** [comment]
按照文档build的，确实是少文件。你ios可以运行？

**Comment by yueyuzhao** [comment]
Yes, of course.

**Comment by yueyuzhao** [comment]
If you build this file successfully, you will see a notification on the top right corner like this:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/2031442/47827500-37397200-ddb9-11e8-95c5-dbd9a60da85b.png">

**Comment by leejuen** [comment]
thank you ,
nom run build
