### ISSUE TITLE
Question: Why we need compile svg to png?

### ISSUE THREAD

**Issue by yueyuzhao** [LLK/scratchjr#200]
Hi @chrisgarrity, we can show images in library in svg format, so is there any particular reason that we must compile svg images in svglibrary to pnglibrary?

**Comment by chrisgarrity** [comment]
@yueyuzhao the svgs caused a performance issue on Android, so we compile them to pngs.

**Comment by yueyuzhao** [comment]
Oh I see, that is a quite reasonable reason. Many thanks for your explanation!

**Comment by yueyuzhao** [comment]
Hi @chrisgarrity, many thanks for your response! But if that is the case, does it mean:
1. We don't have any performance issue on iOS, shall we remove those related functions?
2. Do you have any related article that stressing the performance issue on Android? I make a deep research, but I can't find anything about this. On the other side, I tested on my Android device, but I didn't see any performance downside when replacing png with svg.
Thanks in advance for any feedback.

**Comment by chrisgarrity** [comment]
ScratchJr was available for devices running Android 4.2+. Older devices running 4.2 simply weren't powerful enough to handle the svgs. This was through observation. With the release I just made (today), we now require 4.4+. 4.2 and 4.3 are still supported through the old version, but won't receive any more updates. Unfortunately 15% of our Android users are still on 4.4.x, so requiring 5+ is not currently an option.

**Comment by chrisgarrity** [comment]
@yueyuzhao If you want to work on removing the compile to png step, please do. Ideally iOS and Android are functionally the same, so I would lean towards trying to do everything in svg for both platforms. If that means targeting an Android version > 4.4 let me know.
