### ISSUE TITLE
Build iOS Error

### ISSUE THREAD

**Issue by tomwey** [LLK/scratchjr#205]
When I run iOS, it happens error. 
<img width="445" alt="screen shot 2018-11-09 at 11 01 57" src="https://user-images.githubusercontent.com/522763/48240783-13a4a600-e40f-11e8-9619-e9a9ab7b41a8.png">

**Comment by liyashuang** [comment]
Is pysvg installed?

Install Homebrew.
Run sudo easy_install pysvg to install python svg libraries
Run brew install librsvg to install rsvg-convert
Run brew install imagemagick to install ImageMagick
