### ISSUE TITLE
ScratchJr doesn't pop up as option when trying to open saved file from gmail in Android.

### ISSUE THREAD

**Issue by Andrevn83** [LLK/scratchjr#215]
Hi, 

I am using an LG Gpad 3 8.0 Homeboy tablet
Android version 7.0 January 1, 2017 patch level
Kernel version 3.18.31
Build Number NRD90U
Software version P9451L10a

I am able to share a project via email to my gmail account. When I try to open the file from my gmail account on the same tablet, the option to open from ScratchJr does not appear. Please help as I am starting a summer program class on Monday using the ScratchJr application and I need this functionality for my class.

**Comment by yueyuzhao** [comment]
Duplicate of #158

**Comment by chrisgarrity** [comment]
Closing in favor of #158
