### ISSUE TITLE
Whole window scrolls when dragging blocks to another sprite

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#217]
From Paula B.:
I was trying ScratchJr and I found the following iOS bug (due to changes in Safari):

1. create a  sequence of blocks on one sprite
2. Try to drag that sequence into the thumbnail of another sprite —> the whole windows scrolls.

The way we solve it in TurtleArt is just by adding the following line on the startup routine:

document.body.addEventListener('touchmove', function(e){e.preventDefault();}, {passive: false});

**Comment by chrisgarrity** [comment]
The fix in editor events created a conflict with library scrolling so it was reverted. Reopening the issue to track it.

**Comment by yueyuzhao** [comment]
Hi @chrisgarrity , how about disable WebView scroll in `ViewController.m` ?

**Comment by yueyuzhao** [comment]
Adding line `webview.scrollView.scrollEnabled = false;` to `-webViewDidStartLoad` in `ViewController.m` fixes this issue.

**Comment by HelloRocket** [comment]
Hopefully this whole window scrolling on iOS can be fixed because it drives young students crazy.
As an educator I am happy to hear that there may be a solution in line!

**Comment by chrisgarrity** [comment]
@yueyuzhao thanks for the tip. The issue is that the webview does need to scroll for the assets. I'll need to check if setting this flag still allows the assets (characters and backgrounds) to scroll. There are also places in the parent documentation that need to be able to scroll as well. Since they're all part of the webview it's probably not as simple as turning off scrolling for everything.

**Comment by yueyuzhao** [comment]
Hi @chrisgarrity , I've already tested that it does not affect scrolling for those pages or parts that needs scrolling before commenting on my tablet. It is that simple :). Probably it will be nice for your to have more tests on more devices. Cheers!
