### ISSUE TITLE
ScratchJr freezing on iPad pro

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#239]
Reported from freshdesk 2/11/2020:
Hello, I wonder if you can help. My daughter is an avid user of your scratch jr app, which we use on my iPad Pro (updated to all current versions etc. Recently we are having issue with the app freezing and the home button on the app not responding, also on a recent project the green run flag is replaced by a blue square and the fourth scene on the project is not accessible and has a large black box underneath where the coding blocks should be able to be assembled (see screenshot attached). I wondered if there are any known issues that would affect this? Also is there a maximum number of projects that can be used in the app and is there an easy way to backup the projects without airdropping/emailing each one individually so we could delete and reinstall the app without losing her existing projects?

![image0](https://user-images.githubusercontent.com/399209/74270147-c03b9a80-4cd8-11ea-8b81-6c44914cad6d.png)

**Comment by RobertFiorentino** [comment]
@chrisgarrity Hello! My son is having this same issue on a project he worked really hard on but now it's not working. Did you ever find a solution?

I noticed that it doesn't seem to affect the other projects which makes me thinks just this one might be corrupted. Here are the issues:

1. The green flag doesn't work at all.
2. The third scene doesn't show up on the right panel. In Scene 2 where there used to be a block that led to Scene 3, the block was replaced with a blank end block.
3. Yet when I go into full screen mode, tapping on the right arrow button in the bottom right will actually bring me to Scene 3 (still doesn't play when tapping the green flag though).
4. I can add a new character, but then can't do much after that. If I back out and re-enter the project, I can delete the sprite.

Please let me know if there's a way to fix it. If not, please let me know if there's a way to prevent this from happening in the future (software update, avoid using certain blocks, delete some projects, etc). Thanks!

**Comment by chrisgarrity** [comment]
@RobertFiorentino there isn't a specific limit to the number of projects, but it is limited by the resources of the device. A project with a lot of resources, especially big sounds, can exceed what's available. It is frustrating because it's more likely to happen with a big project that a child spends a lot of time on. I don't know if removing some other projects that you no longer want would help, but it might. I would also check that there's a good amount of space available on the device, and try running with no other applications in memory. Please let us know if you have any success.

**Comment by deepankarmalhan** [comment]
Closing, will reopen if we get more reports of this issue.
