### ISSUE TITLE
Sprite orientation does not reset on Green Flag

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#24]
_From @ChampikaF on November 11, 2014 19:54_

This might require some design discussion - since it's works similarly in iOS. 

When clicking the green flag the sprite's location (x, y) and size are all reset (in lieu of any initialization)...however orientation does not get reset. 

_Copied from original issue: LLK/scratchjr-private#119_

**Comment by deepankarmalhan** [comment]
Closing for #99
