### ISSUE TITLE
Photo does not appear in the face of the sprite

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#240]
The photo filled into the sprite face does not appear on the stage (reported in [freshdesk](https://mitscratch.freshdesk.com/a/tickets/199478))
![bug](https://user-images.githubusercontent.com/399209/75254995-3ea33c80-57af-11ea-95fb-accc2b9145d5.png)

Device info:
BQ Aquaris 10 Tablet 
Android 6.0

**Comment by deepankarmalhan** [comment]
Closing, will reopen if more instances are reported.
