### ISSUE TITLE
Whole background should not scroll on iOS

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#243]
If you drag somewhere in the background of the editor, the whole window scrolls.

![Mar-23-2020 11-27-51](https://user-images.githubusercontent.com/3431616/77334117-c327a300-6cfa-11ea-89d8-03aa4c8359c9.gif)

**Comment by yueyuzhao** [comment]
These pages should also not scroll on iOS: 
![IMG_0942](https://user-images.githubusercontent.com/2031442/77432030-7df99300-6e18-11ea-81c9-5b79873b5d70.PNG)
![IMG_0943](https://user-images.githubusercontent.com/2031442/77432082-8baf1880-6e18-11ea-9996-2d5061ef8e2e.PNG)
![IMG_0944](https://user-images.githubusercontent.com/2031442/77432088-8fdb3600-6e18-11ea-86d3-7dd88bad5972.PNG)
![IMG_0945](https://user-images.githubusercontent.com/2031442/77432113-98337100-6e18-11ea-9aa6-19c8e7515b56.PNG)
