### ISSUE TITLE
Investigate SVG block rendering on Cyanogenmod 12

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#25]
Blocks rendered incorrectly in the PBS Kids version (1.1) on Cyanogenmod 12. See attached screenshots. We were not able to reproduce on Cyanogenmod 11 and do not have access to CM12.

We need help investigating whether this is common to all versions, or unique to the PBS version. 

![screen1](https://cloud.githubusercontent.com/assets/399209/13289650/a28b4fbe-dade-11e5-8800-0d2335c2cdc9.png)
![screen2](https://cloud.githubusercontent.com/assets/399209/13289658/a7a64f8a-dade-11e5-8514-0442bfff5ba6.png)
![screen3](https://cloud.githubusercontent.com/assets/399209/13289660/a9e566be-dade-11e5-9176-42d4e8e9f62c.png)

**Comment by uweiss** [comment]
I can confirm the same strange rendering on my CyanogenMod Version 13 on a Samsung Note 10.1

**Comment by chrisgarrity** [comment]
closing stale issue
