### ISSUE TITLE
Stage Scaling

### ISSUE THREAD

**Issue by klenz39** [LLK/scratchjr#250]
Thank you for your help to port this apps into desktop version. I cant say enough thank you for that. I have a little favor to ask to help me with my teaching. Can you make the stage scaling smaller and larger depending on the screen? We are doing videocall for kids and teaching this. Unfortunately some of the kids has a different screen resolution. I attached the screenshot, when we opened grid version, the lowest row was cut off and can not be seen. I tried to make it full screen and it still does not show. Is there a way to scale it so that it can be shown? Thank you so much.

![image](https://user-images.githubusercontent.com/6107084/77633459-15c6c080-6f82-11ea-8e4a-b6b4efe63376.png)

**Comment by chrisgarrity** [comment]
Hi, the desktop version is an unofficial project of an open source community member. It's not maintained by the Scratch Team, so unfortunately we cannot help with this issue.
