### ISSUE TITLE
Desktop Scratch Jnr - Import file from IOS App

### ISSUE THREAD

**Issue by DumDeeDah** [LLK/scratchjr#257]
Can I load a project created in the IOS app onto the desktop version of Scrtach Jnr? 

If 'Yes', can you please explain how.

Thanks so much.

**Comment by apple502j** [comment]
There is no desktop version.

**Comment by chrisgarrity** [comment]
@DumDeeDah sorry, you may be referring to an unofficial port of ScratchJr by a community member. We do not support that version, and it cannot import projects from the iOS version.
