### ISSUE TITLE
Add import function to ScratchJr

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#258]
On many Android systems, the intent-filter system means that people can't open a ScratchJr file because Android says they don't have anything that can open it even when ScratchJr is installed. And there is no workaround.

Instead, let's just add an import function that would let the user select a file to import, from downloads, drive, etc. It should probably  be similar to what we have in the scratch-android project. I'm not sure it's as big an issue on iOS, but probably should work the same way.

More details about why:

Basically, it's impossible to register an app on Android to handle a custom mime-type. It is possible to define a pattern (e.g. file extension) to read a file. But that only works with downloaded files that have the proper naming. Something attached to an email, or coming from another app like Google Drive, looks only at the mime-type, and the content path is unlikely to have the right name. Depending on your version of Android, you may have a way to browse files, or you may have an app which makes it look like a content stream.

Using the Android intent-filter mechanism the only thing to do is basically say you can open everything, and then deal with errors. Given Android's preference for setting an app as the default when you use it to open anything, that could lead to ScratchJr being considered the default app for a lot of different types, also not ideal.

**Comment by chrisgarrity** [comment]
The simplest thing to do is mimic what the Scratch app does - add an import button in the lobby that opens the standard Android file browser. It lets the user select any file, and then just ignores any that aren't readable with a message. Does that interaction make sense for a 5-7 year old. How comfortable will they be selecting a file? Navigating to the Downloads folder, or perhaps a cloud drive? This feels more like a parent function that we may want to hide from the children.

**Comment by benjiwheeler** [comment]
There was a design discussion about this that surfaced some observations and questions:
* we should do research into app store policies around importing files
* we should reach out to other stakeholders and people in touch with stakeholders around importing
* from a UI design perspective, we agreed that:
    * the Lobby / My projects affords a clarity as it is the area that projects are “managed”
    * it does not make sense to put an icon at the same area/level of focus as the "New Project" plus button, or the existing projects. Instead, a secondary location and level of focus seemed more appropriate
        * draft 1 places an "Import" textual button in between the app-level icon menu and the project thumbnails; here is a very rough draft mockup:
![image](https://user-images.githubusercontent.com/3431616/93801934-c8659c00-fc10-11ea-99c7-0134906d9d85.png)
        * draft 2 places an import icon in the app-level icon menu; we thought this was less ideal because it might lead to unintentional/unnecessary taps, and because import is a project-level function, not an app-level function:
![image](https://user-images.githubusercontent.com/3431616/93802247-314d1400-fc11-11ea-8fda-0713144fdae6.png)

**Comment by benjiwheeler** [comment]
Next step on this: just the first bullet from above, researching into app store policies around importing files

Idea is not to complete this issue right now, but to leave it in a well-scoped state so it can be understood, scheduled, and worked on later.

**Comment by benjiwheeler** [comment]
Update:

Looking at the ios app store guidelines, it seems to me that there is no problem around allowing the import of files. However, depending on your interpretation, it might be necessary to add a "parental gate" before importing:

> The App Store Review Guidelines require apps in the Kids category to use parental gates to prevent kids from engaging in commerce or following links out of an app to websites, social networks, or other apps without the knowledge of their parent or guardian. -https://developer.apple.com/app-store/kids-apps/

Relevant sections of the guidelines: https://developer.apple.com/app-store/review/guidelines/#1.3 , https://developer.apple.com/app-store/review/guidelines/#5.1.4

**Comment by benjiwheeler** [comment]
Removed milestone, because we're not sure when this work will/should be prioritized

**Comment by deepankarmalhan** [comment]
Closing this, it will get tracked in epic created in #460
