### ISSUE TITLE
Scroll position of in-app help pages affect other screens

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#26]
Scrolling to the bottom of the About ScratchJr or Blocks description pages, then switching to a different page (e.g., Home or Settings) doesn't reset the scroll position. On the new (shorter) page nothing is visible until you scroll up.

@tmickel commented:
Scroll position is being stored in file system ("homescroll.sjr")

It seems that the scroll position should be reset when the projects are drawn. But for some reason it appears the value from the in-app help is getting carried over (and then saved into homescroll)

Originally reported in:
https://github.com/LLK/scratchjr-private/issues/461

**Comment by yueyuzhao** [comment]
After some tests, I don't think this is still an issue.

**Comment by chrisgarrity** [comment]
👍
