### ISSUE TITLE
Replace Share by Email button with generic Share

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#262]
Since the original "Share by Email" was implemented, the sharing features on Android and iOS have developed. At this point, the native UI usually shows more options than just email.

https://github.com/LLK/scratchjr/pull/259 starts to implement better flow in Android, but the UI in ScratchJr still says "Share by Email", 

At the least the button should probably just say "Share", and use the normal share icon. Other possible considerations:
* does iOS need a separate Airdrop button, or is that standard in the "Share" feature
* revisit the sharing flow, is there any way to make it easier to use (parental gate is still required by Apple)

Edit May 2021: from a quick look at the latest version, android should just say "Share" and then the share sheet includes options for email, files, drive etc. on iPad, instead of Airdrop it should say "Share" because there are options besides airdrop (files, drive etc.). Email is not one of the options in that list, so it appears that a separate email button is needed for iPad.

**Comment by deepankarmalhan** [comment]
Closing it here, work is being tracked in #489.
