### ISSUE TITLE
Upgrade android.hardware.Camera to android.hardware.camera2

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#27]
_From @tmickel on January 11, 2016 17:18_

This was deprecated in SDK 21, and there's now "android.hardware.camera2"

No idea how hard it would be to switch to the new one, or if it would fix bugs...

_Copied from original issue: LLK/scratchjr-private#446_

**Comment by chrisgarrity** [comment]
We never did this, and I wonder if this is why the camera doesn't work on newer Amazon Fire tablets.

**Comment by yueyuzhao** [comment]
From google https://developer.android.com/training/camera2/capture-sessions-requests

> Note: This page uses camera2 classes. We recommend using the CameraX Jetpack library except when your use case requires access to specific features available only in Camera2. Both CameraX and Camera2 work on Android 5.0 (API level 21) and higher.

**Comment by chrisgarrity** [comment]
Raises a broader question of whether we can just migrate everything to AndroidX.

**Comment by yueyuzhao** [comment]
Guide to migrate to AndroidX:

https://developer.android.com/jetpack/androidx/migrate

**Comment by yueyuzhao** [comment]
> Raises a broader question of whether we can just migrate everything to AndroidX.

There are several libraries that may help:

- Activity: https://developer.android.com/jetpack/androidx/releases/activity
- Sqlite: https://developer.android.com/jetpack/androidx/releases/room
- Camera: https://developer.android.com/jetpack/androidx/releases/camera
- WebView: https://developer.android.com/jetpack/androidx/releases/webkit
