### ISSUE TITLE
Question: why use canvas to render blocks instead of SVG

### ISSUE THREAD

**Issue by sheeeeep** [LLK/scratchjr#273]
I consulted some documents, they think SVG performs better than canvas, especially for mobile devices. 
So I'd like to know the reason for scratchjr use  canvas to render blocks instead of SVG. Thanks.

**Comment by chrisgarrity** [comment]
Older versions of Android (e.g. 4.4) do not support SVGs well, and currently ScratchJr is still available for those systems.
