### ISSUE TITLE
Upgrade to WKWebView on iOS

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#274]
https://developer.apple.com/news/?id=12232019b

The `UIWebView` interface has been deprecated for some time. Apple will stop accepting app updates that use `UIWebView` in December of this year.

Note that we originally didn't update because it required iOS8, and ScratchJr was still supporting iOS 7 at the time. We have since set the minimum iOS required to 8.0, so that's no longer a concern.

**Comment by Mad-hu** [comment]
When can get a new version?

**Comment by chrisgarrity** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prepare for next ScratchJr release](https://trello.com/c/smPwqWp1/137-prepare-for-next-scratchjr-release)

**Comment by yueyuzhao** [comment]
Hi @chrisgarrity, WKWebView is quite different to UIWebView. WKWebView can't call native code and get response directly. It needs a lot of changes, but  I have plenty of experience with this. If no one in your team is working on this, please consider to assign this issue to me. 
BTW, could you please invite me to your boards or team, I can't see the content of the card on Trello.

**Comment by chrisgarrity** [comment]
Hi @yueyuzhao thanks for the message. We are working on this, and you're right there are a lot of changes. Sorry, these are internal projects, so it's team members only on the boards right now.

**Comment by yueyuzhao** [comment]
All right then. If there is anything that I can help, don't hesitate to contact.
