### ISSUE TITLE
How to add Bluetooth connectivity to scratchjr？

### ISSUE THREAD

**Issue by sugar-tong** [LLK/scratchjr#275]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens, screenshots are helpful._

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Device and Operating System

_e.g. iPad mini, iOS 10.3 or Samsung Galaxy Tab S6, Android 10_

**Comment by chrisgarrity** [comment]
@sugar-tong thanks for your question. We're not considering bluetooth connectivity for Scratchjr at the moment, so this is not a question we can answer right now.
