### ISSUE TITLE
ScratchJr desktop app - Screen optimization issue

### ISSUE THREAD

**Issue by vsusmita** [LLK/scratchjr#277]
### Expected Behavior

Should be able to see both Yaxis and Xaxis and the parts should not overlap.

### Actual Behavior

Not able to see X axis, top and bottom parts of the ScratchJr desktop app overlap.

### Steps to Reproduce

You can download scratchJr desktop app from github from this link and simulate.
https://jfo8000.github.io/ScratchJr-Desktop/
Download the windows version

### Device and Operating System

Windows 10,Dell Inspiron 15, 3000 series
![Screen overlap](https://user-images.githubusercontent.com/67329944/85423757-b5e9b100-b594-11ea-9e50-5c448f916461.png)

**Comment by chrisgarrity** [comment]
@vsusmita This is a community supported **unofficial** version of ScratchJr. As mentioned on their page you should file bugs in their version on their issue tracking board: https://github.com/jfo8000/ScratchJr-Desktop/issues
