### ISSUE TITLE
Some SVG images freezes the editor

### ISSUE THREAD

**Issue by fessor2000** [LLK/scratchjr#278]
I have been struggling for a while to figure out why some SVG images do not work with Scratch Jr. When I try to open them in the editor, the app will freeze.

### Expected Behavior

When opening a background or avatar in the editor I should be able to edit it.

### Actual Behavior

When I open the background or avatar in the editor, the app partially freezes. I can still press all the buttons, but nothing happens. I can't draw shapes on top of the image, I can't color in parts of the image, and I cannot get out of the editor by pressing the save and exit button.

### Steps to Reproduce

Unzip [undervand.svg.zip](https://github.com/LLK/scratchjr/files/4869471/undervand.svg.zip) and add the svg image to the svglibrary folder.
Add the information to the media.json file. In this case, add this to the background section:

    {
      "md5": "undervand.svg",
      "width": 480,
      "height": 360,
      "ext": "svg",
      "name": "undervand"
    }

Build the code and start a simulator.
Start a new project.
Choose a new background.
Select the new background and press the edit button.
The app will now freeze as described above.

### Device and Operating System

Tested on an iPad Air 2 (model A1566) with iOS 13.5.1 and on the iPad Pro (11-inch) simulator.

### Recording

[Screen Recording.mov.zip](https://github.com/LLK/scratchjr/files/4869600/Screen.Recording.mov.zip)

**Comment by chrisgarrity** [comment]
ScratchJr was not designed to import **any** svg. Since all of the ScratchJr library images were designed to work in the editor, none of them use gradients to allow them to be more re-colorable by children. I would guess that any use of gradients in your SVG is likely to cause problems.
