### ISSUE TITLE
Camera appears upside down

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#281]
### Expected Behavior

When filling a shape with the camera, it should appear right way up.

### Actual Behavior

The camera starts, using the front facing camera, but the image is upside down. When I switch to the back facing camera the image appears right way up. When I switch back to the front facing camera, the image is right way up as expected.

### Steps to Reproduce

1. Draw a shape
2. Tap the camera icon, then tap the shape to fill the shape with the camera feed.

### Device and Operating System
Google Pixel Slate, Android 9

**Comment by BryceLTaylor** [comment]
@chrisgarrity Do you have any idea about what the impact of this is?  Is it everyone on Android or just a subset of devices?

**Comment by chrisgarrity** [comment]
@BryceLTaylor I think we have had occasional reports of the camera being upside down, but not recently. I think it's probably low impact (Android = ~30% of users, this is a small subset of Android).

**Comment by deepankarmalhan** [comment]
Closing it, keep this in mind for rewrite.
