### ISSUE TITLE
Paint editor calibration problems

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#282]
### Expected Behavior

At any zoom level, but especially at the default zoom level (2x), drawing in the paint editor should appear where you are touching.

### Actual Behavior

We are still getting reports of Android devices where the lines you draw don't match up with your finger (and shapes don't appear where you draw them, fill doesn't work etc). This is an issue to collect reports so that we can try _**again**_ to get this right.

### Steps to Reproduce
1. Open the paint editor
2 draw a shape

### Device and Operating System

From Facebook: [Teaching with Scratch](https://www.facebook.com/groups/TeachingwithScratch) "Acer Tablets", then later confirmed they are chromebooks.

**Comment by Mad-hu** [comment]
+1

**Comment by Mad-hu** [comment]
https://youtu.be/2Mn07KKw4co

**Comment by chrisgarrity** [comment]
@Mad-hu to confirm this is the same bug, if you pinch to zoom out fully, does it draw in the right place. Your video is interesting because it's the first one I've seen where the line is drawn below and to the right of the finger. All the other examples have the line above to the left.

**Comment by Mad-hu** [comment]
you can try it !!    @chrisgarrity 
![image](https://user-images.githubusercontent.com/13977755/97543090-b68eca00-1a02-11eb-99f4-e11acc8eff97.png)

**Comment by chrisgarrity** [comment]
@Mad-hu when we tried that approach [three years ago](https://github.com/LLK/scratchjr/commit/a4737a4399b73f49ee1ab65ee2bc212cd7002d5c), it just changed which android devices were scaling properly. And the problem seemed more common, so we reverted. The question is what device attribute can we check to determine when we need to scale on Android and when we don't

**Comment by chrisgarrity** [comment]
Samsung Galaxy Tab A (SM-T280): Android 5.1.1, Webview 91.0.4472.120: 

starting from new character:
- default zoom: drawing is slightly above and to the left of the finger depending on how far you are from the origin in the upper left. i.e. start in the upper left, it's under the finger, as you move to the right the end of the line gets further to the left of the touch point
- Slightly zoom in before drawing: offset is further above and to the left of the touch point
- Slightly zoom out before drawing: offset is slightly less
- Zoom in a lot before drawing: offset is much further above and to the left - you don't see the lines until you zoom out again
- Zoom out completely, then zoom in to any level: things draw at the right place
- Zoom out completely, then various combinations of zoom, pan (three fingers): sometimes draws in the right place, sometimes not. More often in the right place, but can still get zoomed in and very offset.

When zooming and panning, sometimes the stage is "jumping around" not scrolling smoothly - this seems to sometimes precede the offset getting bad.

**Comment by wsierakowski** [comment]
This is also an issue on Lenovo Tab M10 v2, as presented on the video here: https://www.youtube.com/watch?v=_Zcxgy_uY5s
