### ISSUE TITLE
How to fix LAG with scratch Jr On Pad

### ISSUE THREAD

**Issue by jeffrodriguez1981** [LLK/scratchjr#293]
### Expected Behavior

_Please describe what should happen_
There should be no LAG last time my kids were able to create up to 4 pages of their story now they have only been onto 3 pages and it’s Lagging so much that they are loosing interest. 

### Actual Behavior

_Describe what actually happens, screenshots are helpful._ after creating page 3 when you click the play button or the green flag Movements are very very slow and it LaG

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
First page has 6 characters with individual scripts each ending with the send message block just change different colours 

### Device and Operating System

_e.g. iPad mini, iOS 10.3 or Samsung Galaxy Tab S6, Android 10_
IPad 7th generation iOS 13

**Comment by chrisgarrity** [comment]
Hi, Thanks for the feedback. It would be helpful to have more detail for reproducing the issue or attaching the project (compressed). The issue can be re-opened when we have more data.
