### ISSUE TITLE
Upgrade Android API target to 29 or higher

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#294]
This is just a reminder to update the API target (not the minimum) to 29 or higher. Starting Nov 2, updates are required to be at this level.

**Comment by benjiwheeler** [comment]
We did this to scratchjr-private in https://github.com/LLK/scratchjr-private/pull/581 ; we should update this in this repo.

**Comment by chrisgarrity** [comment]
This has already been partially done. The targetSDK has been changed, but we should also change the compileSdk and build tools to 29, and 20.0.3:
https://github.com/LLK/scratchjr/blob/develop/android/ScratchJr/app/build.gradle#L4-L5
