### ISSUE TITLE
Delete button appears behind the project thumbnail temporarily

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#334]
### Expected Behavior

When you long press on a project in the lobby the red delete button should appear over the project thumbnail.chrisg

### Actual Behavior

The thumbnail image appears "lifted" while you're pressing, and the delete button is behind the image. As soon as you let go the button is on top as expected.
![IMG_0022](https://user-images.githubusercontent.com/399209/95098470-b7328a00-06fc-11eb-85fe-403c7f08a90c.PNG)

### Steps to Reproduce

Long press on a project thumbnail in the lobby.

### Device and Operating System

Confirmed on an iPad mini running iOS 13.5.3

It does NOT happen on iOS 9.3.5

**Comment by yueyuzhao** [comment]
There are 2 more places I find that have the same problem:

- User's made sprite or background on library dialog
- Sprite on stage

After long-pressing images in a WKWebView on iOS 11 and 12 initiates a Drag & Drop session, see [this stackoverflow link](https://stackoverflow.com/questions/49911060/how-to-disable-ios-11-and-ios-12-drag-drop-in-wkwebview) for more detail.
There are solutions that can disable Drag & Drop, but we has drag and drop functionalities in our App, and I haven't try these methods.

But I think replace `<img>` with `<div>` with background will be a better solution.

**Comment by yueyuzhao** [comment]
OK, a better solution, just disabling Drag & Drop on images fix this issue:
```js
img.ondragstart = function () {
    return false;
}
```
