### ISSUE TITLE
Assorted display errors on Android

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratchjr#337]
On some devices, particularly Android 5.0.2, Scratch Jr. has some confusing and distressing display errors. These seem to have appeared before our Sept/Oct 2020 updates.

Examples:

Sprite appears as a distorted version of the background:
![IMG_20201008_145204](https://user-images.githubusercontent.com/3431616/95501834-e6543000-0976-11eb-875b-1986fedbc26d.jpg)

Two copies of the sprite image appear as user touches image (not using the stamp tool)
![IMG_20201008_145222](https://user-images.githubusercontent.com/3431616/95501844-e94f2080-0976-11eb-9c04-e39aa473a368.jpg)

Sprite appears as white silhouette only (also see https://github.com/LLK/scratchjr-private/issues/585 )
![IMG_20201008_145242](https://user-images.githubusercontent.com/3431616/95501850-ec4a1100-0976-11eb-9392-87fc219e09da.jpg)

Two issues displayed: parts of cat sprite appear as white silhouette only; and sprite on the bottom-right displays as bizarre glitch
![IMG_20201008_145302](https://user-images.githubusercontent.com/3431616/95501866-f4a24c00-0976-11eb-846c-d6454aaa39eb.jpg)

Top 1/3 of page backgound and stage appear as solid white
![IMG_20201008_145401](https://user-images.githubusercontent.com/3431616/95501880-f9ff9680-0976-11eb-81a1-f932e1cafc4d.jpg)

**Comment by chrisgarrity** [comment]
@bryce, this is an old device, and we have not seen these issues on newer ones. Android 5.0.2 is less than a half a percent of ScratchJr users, so I think this is low impact. Willing to reconsider if it appears on more devices, but since this wasn't related to the new release I think we'd be hearing about it more.

**Comment by chrisgarrity** [comment]
Additional device with issues: Samsung, Galaxy Tab E 9.6, Android 7.1.1, Wi-Fi

**Comment by chrisgarrity** [comment]
@benjiwheeler @BryceLTaylor several of these issues also show up in the PBS KIDS version so I decided that it would be better to track them as separate issues and close this one. Apparently the white silhouette bug (https://github.com/LLK/scratchjr/issues/393) also appears on iPads.
