### ISSUE TITLE
Schools lose students' work due to Chromebook policies

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#371]
### Expected Behavior

It should be easier to save/export projects to a shared location when a school's policy dictates that user data is cleared when they log off. In general it might be better to give people a way to configure how projects are saved.

### Actual Behavior

ScratchJr saves the project data in the app database. When schools have shared chromebooks, they are often set up to clear the student's data, including all apps, when the student logs off. In ScratchJr this means they lose all projects they've saved. In the current app, they would need to share the project by email, then save it to a place that is not purged, e.g., their Google Drive. Due to the Apple/Google requirements, the share by email is behind a parental gate (math problems), so it makes it harder for children in school to use.

We have also heard that some people have problems opening .sjr files that are saved on drive. The chromebook doesn't recognize the extension as being associated with ScratchJr, so it's not possible to open. See https://github.com/LLK/scratchjr/issues/258 for a way to work around that. 

### Steps to Reproduce
[Example report in FreshDesk](https://mitscratch.freshdesk.com/a/tickets/264059) - sorry only ScratchTeam will be able to see.

### Device and Operating System

ChromeOS

**Comment by deepankarmalhan** [comment]
Make an epic and leave it for now.

**Comment by deepankarmalhan** [comment]
JR-252
