### ISSUE TITLE
unable to open file

### ISSUE THREAD

**Issue by ksdavidc** [LLK/scratchjr#372]
### Expected Behavior
ability to open file

### Actual Behavior
unable to open file

### Steps to Reproduce
try to open file as usual

### Device and Operating System
android 10 or 11 on pixel 3, on android  tablet, on windows 10/mac emulator via bluestack
on both the last recent version and latest oct 7th version of app.

Here is the file, a student project. It was created on an Ipad, I believe. My system is not ipad...

[Project20_20201025_012924.sjr.zip](https://github.com/LLK/scratchjr/files/5433272/Project20_20201025_012924.sjr.zip)

**Comment by ksdavidc** [comment]
by unable to open, I mean, the file switches to scratchjr but never shows up (i.e. with the blue ribbon, etc....). No error or other indicators...

**Comment by chrisgarrity** [comment]
This does look like it may be an incompatibility between iOS and Android. I was able to open the file when I sent it to an iPad. When I tried to open it on Android (5.1.1 Samsung SM-T280), it took a very long time to show the lobby, and the project never appears.

**Comment by yueyuzhao** [comment]
I will dig into this issue tonight. There are a lot of audios(more than 30) in this project, and maybe this is the reason.

**Comment by yueyuzhao** [comment]
This issue can be spit into 2 small issues:
1.  It took a very long time to show the lobby: the App read the project in to memory took a very long time using 
```java
byte[] readByte = new byte[1];
while ((is.read(readByte)) == 1) {
    projectData.write(readByte[0]);
}
```
2.  the project cannot be imported because `E/ScratchJr: JavaScript log, :1, Uncaught ReferenceError: OS is not defined`, the App is not started fully when evaluate `OS.loadProjectFromSjr`

**Comment by ksdavidc** [comment]
thanks! look forward to update and will notify of result. :-)

**Comment by ksdavidc** [comment]
This fix worked...temporarily. See feb 28 issue...

**Comment by ksdavidc** [comment]
[This was incorrectly posted [elsewhere](https://github.com/LLK/scratchjr/issues/268). belongs here.]

@chrisgarrity @yueyuzhao @BryceLTaylor I am sorry to say this has not been fully fixed. I am still getting this error. I posted it in [issues](https://github.com/LLK/scratchjr/issues/394), but the post was summarily ignored (not triaged), so I am trying this route. 

In addition to what is in the post, I should add that I tried several methods of transferring the file, aka via airdrop and via emails, to rule out it being related to that. 

Also, to clarify, the 2nd ipad mentioned could receive and open the files, but when sent from this ipad, they also failed. 

Also note inclusion of 2nd problem related to the home screen. Not sure if related, but it is quite an annoyance. I thought it was just a bluestacks thing, but I confirmed two days ago that it is happening on my student's native Android machine, just not mine! Weird.

For ease of reference, here is the issue post:

I am still getting this problem. It is quite mystifying. I can open some files created by the same ipad, but not others (probably why it appeared to have been fixed). Another ipad was able to open the files. I have tried to open it in android both via bluestacks emulator and natively on the latest android and an old android version. Here they are:

[troubled files.zip](https://github.com/LLK/scratchjr/files/6176151/troubled.files.zip)

Project 33 opens, project 32 doesn't. They were created on the same, fully updated (I believe) ipad within a few days of each other.

There is another problem, possibly related, which is demonstrated in [this video](https://i.imgur.com/PuRiGsS.mp4).

**Comment by yueyuzhao** [comment]
Hi @ksdavidc, sorry for the inconvenience. The merge request is still under review and I'm sure that this problem will be solved on Android devices.

![image](https://user-images.githubusercontent.com/2031442/111989647-035b7480-8b4d-11eb-9f48-735b756926ab.png)

**Comment by ksdavidc** [comment]
Thanks for the upsdate. no problem. and again very sorry for the confusing report path. I was working late and not on all thrusters. :-)

**Comment by chrisgarrity** [comment]
@ksdavidc We're tracking this issue in other places and reopening this issue is just confusing things, so I'm going to close it.
