### ISSUE TITLE
Add Hebrew localization

### ISSUE THREAD

**Issue by liorokman** [LLK/scratchjr#375]
### Expected Behavior

All the localization strings have a Hebrew translation.

### Actual Behavior

The application is usable in Hebrew.

### Steps to Reproduce

Select 'עברית' in the languages menu.

### Device and Operating System

Hopefully all devices and operating systems.

**Comment by chrisgarrity** [comment]
@liorokman unfortunately ScratchJr is not designed to work with RTL languages right now. See #380 There's a lot of preparation that must happen before we can consider adding Hebrew strings.

In addition we use a system called [Transifex](https://www.transifex.com/llk) for managing translations, so we do not accept PRs with language translations.
