### ISSUE TITLE
Add support for RTL languages

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#380]
## Expected Behavior

Currently ScratchJr is not designed for Right to Left languages like Hebrew or Arabic. It would be nice to be able to support them at some point, but it requires a lot more than just providing the strings in one of those langauges.

### Design Questions:
* should the horizontal blocks go left to right or right to left?
* should the green flag be on the upper left?
* does the paint editor UI need to be flipped horizontally?
* review all the icons with an implied direction. e.g. Grow shows a person getting bigger LTR. If the direction of the blocks change, then many of the icons must change too.

### Preliminary list of UI changes:
* blocks categories should be on the right with the blocks palette on the left
* blocks in the blocks palette should be right aligned, with undo/redo on the left and flipped in order (undo on the right)
* put the list of characters to the right of the stage, and the list of pages to the left of the stage
* lobby: have the add project button in the upper right, and projects orders RTL
* lobby: reverse the order of all the navigation icons/logo
* help and reference pages: make sure that text is formatted correctly in RTL (e.g. headers are on the right not left)
* asset libraries: reverse the top menu bar and list the assets RTL

**Comment by deepankarmalhan** [comment]
Already part of project accessibility guidelines, closing this out.
