### ISSUE TITLE
This error occurred in iOS compilation

### ISSUE THREAD

**Issue by ToJ-Coder** [LLK/scratchjr#382]
internal/modules/cjs/loader.js:1068
  throw err;
  ^

Error: Cannot find module '/Users/vipcode/Desktop/scratchjr-develop/node_modules/webpack/bin/webpack.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1065:15)
    at Function.Module._load (internal/modules/cjs/loader.js:911:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
building file list ... done

sent 140 bytes  received 20 bytes  320.00 bytes/sec
total size is 525092  speedup is 3281.82
building file list ... rsync: link_stat "/Users/vipcode/Desktop/scratchjr-develop/ios/../editions/free/src/app.bundle.js" failed: No such file or directory (2)
rsync: link_stat "/Users/vipcode/Desktop/scratchjr-develop/ios/../editions/free/src/app.bundle.js.map" failed: No such file or directory (2)
done

sent 7401 bytes  received 20 bytes  14842.00 bytes/sec
total size is 20668344  speedup is 2785.12
rsync error: some files could not be transferred (code 23) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/main.c(996) [sender=2.6.9]
Traceback (most recent call last):
  File "../bin/convert-svg-to-png.py", line 5, in <module>
    import pysvg.parser
ImportError: No module named pysvg.parser
Command /bin/sh failed with exit code 1

**Comment by chrisgarrity** [comment]
Please make sure that you have installed npm and node as required and run `npm install` before trying to build either iOS or android versions.

If the app.bundle.js is still missing, try running `npm run build` in the root directory to force the javascript bundle to be built.
