### ISSUE TITLE
screen flickers and object disappears when moving the object

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#387]
### Expected Behavior

Object should be able to be moved without disappearing. 

### Actual Behavior
https://user-images.githubusercontent.com/399209/108259713-71b4ad80-712f-11eb-9358-a57825fb828b.mp4

Would be good to have a way to reproduce this in the base ScratchJr

### Steps to Reproduce
1. Open app
 2. Click new project
 3. Choose object
 4.Scroll up page

Note: clicking on the currently selected object a second time is expected to add it to the project

### Device and Operating System
Samsung, Galaxy Tab E 9.6, Android 7.1.1, Wi-Fi

_Note: this was reported for the PBS KIDS edition, but I'm logging this in the main ScratchJr issues in case it applies to all editions._

**Comment by BryceLTaylor** [comment]
The priority 2 label added to this issue is to get repro steps.  It should be re-prioritized when we know the impact.

**Comment by chrisgarrity** [comment]
Right now we're not seeing these issues in the latest version. Closing and will reopen if we get new reports.
