### ISSUE TITLE
Loading animation is missing for story starters

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#390]
### Expected Behavior
The PBS KIDS logo should appear and get "filled" in front of a greyed out background while the project. loads.

### Actual Behavior

https://user-images.githubusercontent.com/399209/108263593-7af44900-7134-11eb-9fbd-78699f9a3f76.mp4

### Steps to Reproduce
1. Launch the app
2. Click on Start
3. Click on Story Starters and observe

### Device and Operating System
Samsung, Galaxy Tab A 10.1, Android 8.1, Wi-Fi

**Comment by yueyuzhao** [comment]
I was unable to reproduce this issue, but if I comment `Project.addFeedback`, then it shows just like the issue shows. I thinks this is related, but I can't figure out what is wrong. 
```javascript
if (loadIcon.complete) {
    Project.addFeedback();
} else {
    loadIcon.onload = function () {
        Project.addFeedback();
    };
}
```

```javascript
static addFeedback () {
    var body = gn('modalbody');
    newHTML('div', 'loadscreenfill', body);
    newHTML('div', 'topfill', body);
    var cover = newHTML('div', 'loadscreencover', body);
    cover.setAttribute('id', 'progressbar');
    var topcover = newHTML('div', 'topcover', body);
    topcover.setAttribute('id', 'topcover');
    var cover2 = newHTML('div', 'progressbar2', body);
    cover2.setAttribute('id', 'progressbar2');
    var li = newHTML('div', 'loadicon', body);
    li.appendChild(loadIcon);
}
```
