### ISSUE TITLE
Character is partially hidden when fill is applied in the paint editor.

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#392]
### Expected Behavior

Character should be visible while editing the shapes

### Actual Behavior

https://user-images.githubusercontent.com/399209/108265412-bc85f380-7136-11eb-8405-2ba29d415c84.mp4
### Steps to Reproduce

1. choose a character and open the paint editor
2. Choose dots 
3. Choose color and apply
4. 
### Device and Operating System

Samsung, Galaxy Tab E 9.6, Android 7.1.1, Wi-Fi

_Note: this was reported for the PBS KIDS edition, but I'm logging this in the main ScratchJr issues in case it applies to all editions._

**Comment by BryceLTaylor** [comment]
The priority 2 label added to this issue is to get repro steps.  It should be re-prioritized when we know the impact.

**Comment by benjiwheeler** [comment]
I am able to reproduce this:
* Android System WebView version 85.0.4183.101
* android v 5.0.2
* unsure my ScratchJr version

Steps:
* force quit ScratchJr if running
* start ScratchJr, click on Home
* create new project
* tap sprite + and select Tac sprite (purple blob character)
* tap paintbrush icon to edit Tac appearance
* tap Tac on cheek to paint fill

result: top half of paint editor area becomes white, obscuring Tac's top half and background

note that this only happens the first time I paint fill -- all subsequent attempts do the normal thing, until I start a new project. Even adding a new Tac sprite to the project, I cannot reproduce the problem.

**Comment by chrisgarrity** [comment]
@BryceLTaylor now that we have a repro case I'm removing the priority so it can get re-triaged.

**Comment by chrisgarrity** [comment]
Right now we're not seeing these issues in the latest version. Closing and will reopen if we get new reports.
