### ISSUE TITLE
On ipadpro sprite is white silhouette at edge of stage

### ISSUE THREAD

**Issue by MissCate** [LLK/scratchjr#393]
### Expected Behavior

sprite should be visible in color at all locations on stage before and after program stops.

### Actual Behavior
https://user-images.githubusercontent.com/79463406/108727418-8f4e9200-74f6-11eb-8a5a-6c2e7238bb9c.MP4
![Screenshot 2021-02-22 at 10 15 27 AM](https://user-images.githubusercontent.com/79463406/108728052-2d425c80-74f7-11eb-9b56-7554306cb8fa.png)

sprite becomes white silhouette if it lands in the right 20% or so of stage when the program stops.

### Steps to Reproduce

place sprite anywhere on stage, program it to go to right edge. It will white out after program stops. then program it to move away and it will come back to color.

### Device and Operating System

ipad pro 3rd gen/ Model # MTFL2LL/A       OS 14.4

**Comment by yueyuzhao** [comment]
Note that I can't reproduce this issue on iPad or Android tablets, but I reproduced this on macOS edition.
