### ISSUE TITLE
Unable to open this file using latest version of everything

### ISSUE THREAD

**Issue by ksdavidc** [LLK/scratchjr#394]
### Expected Behavior
_Please describe what should happen_
This project should open with blue ribbon
### Actual Behavior
_Describe what actually happens, screenshots are helpful._
I had this problem (**only** on files created from **this ipad.** Other ipads did not generate the problem) about 3 weeks ago and had student upgrade ipad and scratchjr. Then it worked  for a week. Now it is not working again. 
opening file switches to opened instance of scratch jr, but nothing happens. Tried opening via airdrop on mac and via email on mac and pixel. 

### Steps to Reproduce
_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
open attached file via email on android, or via airdrop/bluestacks on mac.
### Device and Operating System
_e.g. iPad mini, iOS 10.3 or Samsung Galaxy Tab S6, Android 10_
macs (running bluestacks 4.106 and big sur and high sierra) and pixel 3a running latest android. 

These don't work
hijklmnopqrstuvwxyz.sjr
abcdefg.sjr
abcdefg2.sjr
[Not working.zip](https://github.com/LLK/scratchjr/files/6055147/Not.working.zip)

This one (I believe) from same computer did last week:
mao.sjr
[working project.zip](https://github.com/LLK/scratchjr/files/6055156/working.project.zip)

**Comment by ksdavidc** [comment]
I am still getting this problem. It is quite mystifying. I can open some files created by the same ipad, but not others. Another ipad was able to open the files. I have tried to open it in android both via bluestacks emulator and natively on the latest android and an old android version. Here they are:

[troubled files.zip](https://github.com/LLK/scratchjr/files/6176151/troubled.files.zip)

Project 33 opens, project 32 doesn't. They were created on the same, fully updated (I believe) ipad within a few days of each other.

There is another problem, possibly related, which is demonstrated in [this video](https://i.imgur.com/PuRiGsS.mp4).

**Comment by deepankarmalhan** [comment]
Closing for now, will reopen if there's new instances.
