### ISSUE TITLE
ScratchJr Audio interrupts background audio

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#395]
Feedback from a user:

> I've started using Scratch Jr. with my young child, and we have a point of major frustration with the app. The user interface sounds that are played when interacting with most elements will stop background audio. This means that we cannot listen to an audiobook or music while playing in Scratch Jr.

### Expected Behavior

Sound effects for UI interactions should not interrupt sounds from other apps playing in the background. Question: what should happen when playing back recorded sound? 

### Actual Behavior

ScratchJr stops all other sounds.

Advice that ought to work if Scratch Jr. plays audio through native iOS mechanisms:

This documentation from Apple shows that an application can configure its "Audio Session" when the app starts: https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/configuring_the_audio_playback_of_ios_and_tvos_apps

Specifically, Scratch Jr should probably have a "playback category" set to "ambient". See https://developer.apple.com/documentation/avfaudio/avaudiosession/category/1616509-playback

### Steps to Reproduce
Need to confirm repro steps. Presuming:
1. start audio playing in another app (e.g. play music) that continues in the background
2. start ScratchJr, observe that sound effects like adding or removing blocks in the editor interrupt background

### Device and Operating System

iPad

**Comment by deepankarmalhan** [comment]
Donald can help if he has capacity.

**Comment by deepankarmalhan** [comment]
Released a fix in v1.4.14
