### ISSUE TITLE
How-to Video does not play

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#399]
### Expected Behavior

The How-to video (from the launch screen or the help screen) should play when you tap the play button on iOS.

### Actual Behavior

The video doesn't play. 

### Steps to Reproduce
Note: this only seems to happen in the PBS KIDS edition, so it might be specific to that video somehow.

1. Tap the help button (light-bulb), and then the play button under "Quick Intro" to open the video
or
1. Tap the "How-to" button on the launch screen ('?' in official ScratchJr)
2. Tap the play button on the video

### Device and Operating System

- iPad mini4 iOS 13.5.1
- iPad Air

**Comment by yueyuzhao** [comment]
I tried, but the video plays well on both my iPad mini 2(iOS 12.5.2) and the simulator(iOS 14.1):

![image](https://user-images.githubusercontent.com/2031442/119662623-2c0d2c80-be64-11eb-9211-65e5c66523f9.png)

**Comment by yueyuzhao** [comment]
Hi @chrisgarrity , I tried playing the video on iPad mini 4 simulator with iOS version 13.0, 13.1, 13.2.2, 13.3, 13.4, 13.5, 13.6 and 13.7, but couldn't reproduce this issue. 
By the way, I suggest that we integrate some third party libraries like [sentry](https://docs.sentry.io/platforms/javascript/) or [bugsnag](https://docs.bugsnag.com/platforms/javascript/) to track JavaScript issues although this may be not a JavaScript issue.

**Comment by chrisgarrity** [comment]
@yueyuzhao I'll take this one to try to reproduce.

**Comment by chrisgarrity** [comment]
This one is also working for me. I'm not sure what else changed, but I'm closing until we can reproduce it.
