### ISSUE TITLE
Characters should not disappear when dragged

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#400]
### Expected Behavior

Characters should be visible when dragged.

### Actual Behavior
Characters disappear when dragged. 

https://user-images.githubusercontent.com/399209/111786915-b6e60f80-8894-11eb-8a6f-6942038c787f.mp4

Note, also shows #393 where sprites turn white when at the edge of the screen.

### Steps to Reproduce

I'm not quite sure what the person in the video did to get into that state, and I have not been able to reproduce on the devices I have available.

### Device and Operating System

Samsung, Galaxy Tab E 9.6, Android 7.1.1, Wi-Fi

**Comment by BryceLTaylor** [comment]
The priority 2 is to get repro steps.  It should be re-prioritized when we know the impact.

**Comment by benjiwheeler** [comment]
I am unable to reproduce this reliably or precisely on:

* Android System WebView version 85.0.4183.101
* android v 5.0.2
* unsure my ScratchJr version, but it is regular ScratchJr, not PBS version

Note that I can see strange behavior when dragging sprites (though I must add at least one sprite to see it; if just the default cat, I see no problem); sprites switch appearance to other costumes, even ones from other projects that have recently been open!

However, I can't seem to get the white-filled version of sprites to appear.

**Comment by chrisgarrity** [comment]
Right now we're not seeing these issues in the latest version. Closing and will reopen if we get new reports.
