### ISSUE TITLE
Characters should not change visually when dragged

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#401]
### Expected Behavior

Characters being dragged should not change to another character in the scene.

### Actual Behavior

After adding several characters including the tulip and apple, when dragging the tulip to the edge of the stage it changes to show the apple, then changes back to tulip when dragged into the middle of the stage.

https://user-images.githubusercontent.com/399209/111789195-42f93680-8897-11eb-80fc-29b4fe52eb7e.mp4

### Steps to Reproduce

Need more information, I have not been able to reproduce this on the devices I have available.

### Device and Operating System

Samsung, Galaxy Tab E 9.6, Android 7.1.1, Wi-Fi

**Comment by BryceLTaylor** [comment]
Priority 2 is to find reproduction steps.  It should get reprioritized when we have them.

**Comment by benjiwheeler** [comment]
I am able to reproduce this:

* Android System WebView version 85.0.4183.101
* android v 5.0.2
* unsure my ScratchJr version, but it is regular ScratchJr, not PBS version

repro steps:
* force quit ScratchJr if running
* start ScratchJr, click on Home
* create new project
* tap sprite + and select Tac sprite (purple blob character); select check mark
* drag Tac around; appearance does not change
* drag Scratch cat around; appears to become Tac
* drag Tac around; appears to become Scratch Cat
* drag Scratch cat... etc.

Also note that the top 1/3 of the screen becomes partially covered with a white rectangle, obscuring the stage and background but not icons or buttons

**Comment by yueyuzhao** [comment]
Hi @benjiwheeler ,

I was unable to re produce this issue although I install WebView of version 85.0.4183.101 on my android 6.0 tablet, but I guess what might cause the problem is `Stage.whoIsIt`.

I created a [PR](https://github.com/LLK/scratchjr/pull/441) that uses `Document.elementFromPoint` to the current sprite when touch start and use the original detector after the grid is on, also I show the debugging area on the left bottom of screen for us to see what's going on on the `workingCanvas`. So could you please give it a try? 

I look forward to your reply. 
Thanks

**Comment by yueyuzhao** [comment]
From https://caniuse.com/?search=elementFromPoint, we can use this `elementFromPoint` feature if needed.

**Comment by yueyuzhao** [comment]
Another possible reason is memory leaks in WebView. The memory are not cleaned up after page changed. I tried to use a new WebView instance for each page, and release the old one, again no good luck.

I will try to obtain a device that can run and choose WebView version first. All of my devices at hand have no option of WebView in the `Developer Options` page, and I can't enable it in `WebView DevTools` after run `adb shell am start -a "com.android.webview.SHOW_DEV_UI"`.

**Comment by chrisgarrity** [comment]
Right now we're not seeing these issues in the latest version. Closing and will reopen if we get new reports.
