### ISSUE TITLE
Sound files prevent file from being shareable

### ISSUE THREAD

**Issue by ksdavidc** [LLK/scratchjr#407]
### Expected Behavior

sending file via email or airdrop should work.

### Actual Behavior

The file open operation goes to scratchjr, but hangs there, never importing the file.

### Steps to Reproduce

Create a file with *several* sound recordings. Perhaps it is the length, quantity, or something else. "small" sound files seem to work. send it and try to open it. 

Attached files. The first one (testofaudio) is a blank project with just one audio. It can be sent and received with no problem. The second (marked 25) is this original file with 4 more audio added. It does not open.
[test of audio.zip](https://github.com/LLK/scratchjr/files/6372771/test.of.audio.zip)

### Device and Operating System

ipads and android both, mostly android. I have one instance of someone being able to send to themselves, but usually even this doesn't work.

**Comment by deepankarmalhan** [comment]
Will close but if there are new repro instances then we will reopen it.
