### ISSUE TITLE
Can'T return to home screen. The scratch and home buttons inoperative.

### ISSUE THREAD

**Issue by ksdavidc** [LLK/scratchjr#408]
### Expected Behavior

clicking scratch or home buttons should return me to main screen

(I mentioned this before in a separate issue, but it has become so prevalent, I am relegating it to its own issue.)

### Actual Behavior

Pressing those buttons inoperative. Leaving the application and returning will return you to the main screen but projects are not visible (often). Pressing the scratch button at this point will give you the welcome screen, and pressing the home button on this will finally return you to the home screen with projects visible. Here is a gif [Imgur](https://i.imgur.com/PuRiGsS.mp4). I have to do this every time to get out of a project.

### Steps to Reproduce

No idea what makes it happen. It doesn't at first, but once it happens, it happens consistently. 

### Device and Operating System

iPad and android, latest versions and old versions.

PS  One problem is that it is impossible to just try and reinstall scratchjr, because one loses all one's data. Scratchjr needs a better, aka more normal, file management system. Copying a file is a roundabout hassle (email it to myself? are you kidding? that's the easiest way?), sharing a convoluted obscurity (google drive -- really?? yeah, my 6 year old understands google drive), and consistent naming and renaming is obfuscated (by the fact that the name of the file and the name of the project don't coincide). (pardon the snarky exaggeration. it is only to make a point, not intended to offend or be disrespectful.) I expect there may be reasons or rationales for it being the way it is, but it is, in practical terms, for a regular user, quite unfortunate.

PPS this and my latest issue #407 are, shall we say, irksome. They did not seem to appear when I started with this last year, but this year they are more prevalent. I don't know if this is because I didn't notice it or I have more students using scratchjr more and in different ways, or if it is a recent update bug. Maybe it's the covid (just kidding). Anyway, I know things take time, but I just want to say I am really hopeful that you hardworking devs can find a fix :-) It would make such a huge difference for us!!

**Comment by chrisgarrity** [comment]
Sorry, we can't reproduce this on any of our supported devices.
