### ISSUE TITLE
Desktop/Web Client?

### ISSUE THREAD

**Issue by justisGipson** [LLK/scratchjr#410]
### Expected Behavior

_Please describe what should happen_

Scratch Jr. in the browser? Will this ever be a thing?

### Actual Behavior

_Describe what actually happens, screenshots are helpful._

We've got a huge number of students using scratchjr and a majority of them do not have touchscreen devices. They're all on chromebooks (NO touch screen). Will a web version ever happen? I know the extension is going to go away eventually, as its been unsupported for a while now.

Or if there's ways to implement these changes ourselves... we would be totally happy to do it.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Device and Operating System

_e.g. iPad mini, iOS 10.3 or Samsung Galaxy Tab S6, Android 10_

**Comment by justisGipson** [comment]
I also imagine if #222 is resolved, this may fix quite a few of these issues... which was related to #160

Hope to see some traction with this. Let me know if I can contribute to this at all. I've got my own fork of SJR going, definitely not an easy task.

**Comment by chrisgarrity** [comment]
@justisGipson thanks for the input. We know that making ScratchJr available online would be a big help to many people, but there are several issues that must be fixed first. We don't track a whole new version as a github issue, so I'll be closing this.

**Comment by justisGipson** [comment]
@chrisgarrity ok, cool

But my to my original question, will this ever be a thing? I'm going to continue my work on my fork of this, because we have hundreds of customers using SJR, on chromebooks with no touchscreens.
