### ISSUE TITLE
Include all assets when exporting projects

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#413]
### Expected Behavior

Upgrading to a new version of ScratchJr should not break existing projects or prevent importing projects created in an earlier version.

### Actual Behavior
In the first version of ScratchJr we decided not to export any assets that were already included in the library to reduce the size of the exported file. However, that means that when we change the libraries we have to keep all the previous assets in the library - increasing the size of the app for everyone, not just people who have older projects.

We did have some plan for this, and there is a "version" field in the exported project. However, it is hardcoded as "iOSv01", and it really looks like it should provide metadata information about the version of scratchjr that was used to create the file. The asset libraries do not change very often, so there should be a field that is specific to the asset libraries that should also be specific to the edition of ScratchJr, e.g. the libraries for PBS Kids will not change at the same time as official scratch, so they will need their own setting.

### Steps to Reproduce

You can actually reproduce this right now by exporting a project from the published ScratchJr app (using any asset other than the start) and trying to open it in the open source version 

### Proposed changes
After discussing the various options, including checking a version field and rejecting incompatible files, we decided that we should start exporting all assets in the exported project, not just user created ones. Then the imported file is complete, and not dependent on which version of the library the app has installed. We should still add a setting to identify the library version, but it shouldn't cause a file to be rejected.

- Export: copy all assets into the zip file
- Import: check the md5 - if an identical md5 already exists in the app, then no need to duplicate. 

Add a new item to the [settings.json file](https://github.com/LLK/scratchjr/blob/develop/editions/free/src/settings.json) for `"assetLibraryVersion":  "assetLib v01"`

Provide the asset library version as metadata when exporting a project.

On startup provide the current asset library version to the native code.

When importing a project assume that any project without the assetLibraryVersion value is version "0". 

Debatable: should the version be "v1.0" or just "v01"? Is there any benefit to being able to increment library minor version?

We should also handle the opening a project failure better, but that's a [separate issue](https://github.com/LLK/scratchjr/issues/412).

**Comment by yueyuzhao** [comment]
Hi @chrisgarrity , I'm working on this, but two questions need to be clear:
1. Do all editions including PBS need this feature? If not we may need to add an item to `settings.json`.
2. Sharing for edited sample projects in PBS edition is enabled, are these assets going to be copied?

**Comment by chrisgarrity** [comment]
@yueyuzhao good questions. 

1. Yes, all editions including PBS will need this feature. 
2. Yes, once the sample project has been saved as a regular project, it should include all assets in the export.

These changes are needed because we'll have changes to the standard libraries for both PBS and Official versions in the next 12 months.
