### ISSUE TITLE
non-open source editions should not be hard coded in this repository

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#414]
### Expected Behavior

There are elements of ScratchJr that are unique to each edition - the current version number, the application id, the mimetype, the extension that should be used for export etc. They should not be hard coded in the source. Ideally there would be configuration settings for each edition that are then used in the app. 

### Actual Behavior
In many places code is hard coded for the particular application id. For example, this sets the extension based on comparison with the current bundle id. It will be very brittle for new editions or if things like the extension or mimetype change:

https://github.com/LLK/scratchjr/blob/develop/android/ScratchJr/app/src/main/java/org/scratchjr/android/ScratchJrUtil.java#L54-L58

**Comment by deepankarmalhan** [comment]
Closing it, something to keep in mind in rewrite.
