### ISSUE TITLE
Couldn't export project when name contains single quote

### ISSUE THREAD

**Issue by yueyuzhao** [LLK/scratchjr#430]
### Expected Behavior

Project with name containing single quote `'` shall be export normally

### Actual Behavior

The loading icon shows and nothing happens.

### Steps to Reproduce

1. create a new project
2. click right top corner to show project info
3. add a single quote to project name
4. try to share it

### Device and Operating System

iOS

**Comment by deepankarmalhan** [comment]
SJRW-123
