### ISSUE TITLE
Sprite appears as distorted version of background

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#443]
Originally reported as part of #337 

![IMG_20201008_145204](https://user-images.githubusercontent.com/3431616/95501834-e6543000-0976-11eb-875b-1986fedbc26d.jpg)

* Samsung Galaxy Tab 4?
* Android System WebView version 85.0.4183.101
* android v 5.0.2

**Comment by yueyuzhao** [comment]
The play/stop button on the top right corner is also wrongly displayed.

**Comment by chrisgarrity** [comment]
Right now we're not seeing these issues in the latest version. Closing and will reopen if we get new reports.
