### ISSUE TITLE
Characters partially displayed

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#448]
Originally reported as part of #337 

Two issues displayed: parts of cat sprite appear as white silhouette only; and sprite on the bottom-right displays as bizarre glitch
![IMG_20201008_145302](https://user-images.githubusercontent.com/3431616/95501866-f4a24c00-0976-11eb-846c-d6454aaa39eb.jpg)

White silhouette may be related to #393

* Samsung Galaxy Tab 4?
* Android System WebView version 85.0.4183.101
* android v 5.0.2

**Comment by deepankarmalhan** [comment]
Closing since it will be tracked in Epic created in #454
