### ISSUE TITLE
Remove obsolete code for Android 4.2 and 4.4

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#450]
The minimum supported Android version for the current ScratchJr is 5.0+. There is still code that is just to work around Android 4 issues, and it should get removed.

Non-exhaustive list:

- https://github.com/LLK/scratchjr/blob/f226f3fdc42e369b3df7144909cd8dfbe01c61b9/src/editor/blocks/BlockArg.js#L181-L185
- https://github.com/LLK/scratchjr/blob/f226f3fdc42e369b3df7144909cd8dfbe01c61b9/src/editor/blocks/BlockArg.js#L196-L200
- https://github.com/LLK/scratchjr/blob/f226f3fdc42e369b3df7144909cd8dfbe01c61b9/src/editor/blocks/BlockArg.js#L196-L200
- https://github.com/LLK/scratchjr/blob/f226f3fdc42e369b3df7144909cd8dfbe01c61b9/src/editor/blocks/BlockArg.js#L363-L366
- https://github.com/LLK/scratchjr/blob/f226f3fdc42e369b3df7144909cd8dfbe01c61b9/src/editor/engine/Sprite.js#L313-L328
- https://github.com/LLK/scratchjr/blob/f226f3fdc42e369b3df7144909cd8dfbe01c61b9/src/editor/ui/Project.js#L100
- https://github.com/LLK/scratchjr/blob/f226f3fdc42e369b3df7144909cd8dfbe01c61b9/src/editor/ui/Project.js#L113
- https://github.com/LLK/scratchjr/blob/f226f3fdc42e369b3df7144909cd8dfbe01c61b9/src/editor/ui/Project.js#L294
-

**Comment by deepankarmalhan** [comment]
In the rewrite, we will make sure to not have Android 4 specific code in the blocks code.
