### ISSUE TITLE
Trackpad/mouse affordances

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#461]
Collecting questions related to supporting non-touchscreen devices with a trackpad or mouse. Eventually any changes should get their own issue.

- Deleting items: should right click be available for deleting? Or duplicating? pop up menu would need to be icons, not words
- Should cursor turn into pointer finger when over something that you can interact with using a trackpad
- scrolling the character list with a mouse scrollwheel, it gets a bit stuck at the top
- Are there other hover states that we should add?

**Comment by deepankarmalhan** [comment]
Setting up a meeting with design team and DevTech team to figure out these design question.
