### ISSUE TITLE
Number input doesn't accept keyboard input

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#462]
### Expected Behavior

Can we accept input from the keyboard, but limit the input to just numbers. Will it feel broken if you try to type a character like 'a' and nothing happens? If you have a keyboard should it pop up the soft numberpad at all?

### Actual Behavior

If you click into number input field (e.g. move 1 step), you cannot use the keyboard to enter a value. You still need to click buttons on the soft numberpad

### Steps to Reproduce
On a device with a keyboard
1. drag out a move block
2. Click in the number field to popup the soft numberpad
3. try to type a number - nothing happens.

### Device and Operating System

Chromebook

**Comment by deepankarmalhan** [comment]
SJR-169
