### ISSUE TITLE
Reshape tool in paint editor can't add points to some sides of shapes

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratchjr#465]
### Expected Behavior

Tapping any side of a shape (Circle, Square, Triangle, etc.) should add a point.  

### Actual Behavior

Some segments of shapes will not receive a new point if you tap it.  

- On a newly drawn square  it is the top and right segments that can't receive points.  
- On a newly drawn circle it is the upper left and upper right segments.  
- On a triangle it is the upper left and upper right, but if you tap the bottom, the first time, it adds a point on the upper right side.  A second tap on the bottom segment adds a point on the bottom segment.  The behavior of adding points to a triangle becomes less predictable after the second new point.

### Steps to Reproduce

Open the paint editor
Draw a new shape
Try to add points to the various sides of the shape (See above)

### Device and Operating System

iPad mini 5 running iOS 10.14.  Not reproducible on older ipads running older versions of iOS

**Comment by BryceLTaylor** [comment]
We could only see this on one of our test devices, so it's hard to know the impact of this issue.  If anyone can reproduce this on other devices it would be useful for us to know the model and os versions.

**Comment by deepankarmalhan** [comment]
Closing out since this is fixed in #504
