### ISSUE TITLE
Cannot zoom in the paint editor with a mouse

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#472]
### Expected Behavior

There should be a way to zoom on devices without a touchscreen or trackpad.

### Actual Behavior
Paint editor zoom requires multi-touch. It works on touch screens and trackpads. 

Most chromebooks have touchpads, so even if you have a mouse attached, there is still a way to zoom. 

Needs design - what is an accessible zoom control for children?

### Device and Operating System

Android tablet with a mouse plugged in.

**Comment by deepankarmalhan** [comment]
Maybe have a +/- or have a slider attached to use with mouse in the paint editor.

**Comment by deepankarmalhan** [comment]
SJR-165 and SJR-167
