### ISSUE TITLE
Cannot drag with a mouse/trackpad with the grid turned on

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#473]
### Expected Behavior

Dragging with a mouse or trackpad should work with the grid enabled.

### Actual Behavior
When the grid is enabled, you can only drag a character around the stage with touch.

### Steps to Reproduce

- Have at least one character on the stage
- turn on the grid
- try to move the character by clicking and dragging with the mouse/trackpad - observe the character does not move
- try to move the character by touch and dragging - observe the character moving.

### Device and Operating System

Android tablet with mouse plugged in and Chromebook

**Comment by deepankarmalhan** [comment]
SJR-164
