### ISSUE TITLE
Random flicker on the lower half of the editor on Chromebooks

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#475]
### Expected Behavior

Display should not flicker

### Actual Behavior

Every now and then in the editor, on a chromebook, there is a brief flash on the lower half of the screen. Like some element appears and disappears. I have only seen this on chromebooks with vey high DPI screens. Mostly logging this so we can track whether it appears on other (lower end) devices.

Note: I also realized that I've only seen it on ChromeOS devices that have detachable keyboards to convert to a tablet. You can see it in the slow-motion video below, and the still is one frame.

https://user-images.githubusercontent.com/399209/126560663-d742efc8-b721-4799-a4b9-b6ca2369e978.mp4

![PXL_20210721_210332032_exported_28140](https://user-images.githubusercontent.com/399209/126560670-5370c486-7732-4d5c-accc-e22fc817897c.jpg)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Device and Operating System

HP Chromebook x2 Android 9

**Comment by chrisgarrity** [comment]
Note, there have been reports of similar flickers when Chromecasting from a Chromebook to a large screen, and on some other low end devices. We're collecting additional data from the users.

**Comment by deepankarmalhan** [comment]
If Donald has capacity he can help with this.

**Comment by deepankarmalhan** [comment]
SJR-163
