### ISSUE TITLE
Visual feedback for add sprite button is flaky

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#476]
### Expected Behavior

When you tap the add character button in the editor, there should be a brief visual cue (grey highlight) that the button has been tapped before the library appears.

### Actual Behavior

iOS: sometimes (first time perhaps?) the grey overlay remains visible on the library screen
Android: grey overlay never appears. 

### Steps to Reproduce
Android: tap the add character button - you hear the tap sound, but there is no visual cue
iOS: difficult to reproduce - may be a timing issue?

**Comment by deepankarmalhan** [comment]
Added as a project requirement (accessibility requirement), closing this out.
