### ISSUE TITLE
Doubled numbers in block inputs

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#482]
### Expected Behavior

entering numbers in block inputs should correspond to the numbers tapped.

### Actual Behavior

We had a report from a person who is getting doubled numbers when they try to enter them.

> I've started using Scratch with my son, but have found that when we try to put in number values that each number is being duplicated. For example, if I wanted a character to move two spaces, when I hit the number 2, I got 22. When I hit 3 I get 33. When I hit 4 I get 44. Any suggestions? This issue is not showing up when using the calculator application. I did try to uninstall and then to reinstall the application, but the issue persists.

Logging this issue to track if we see it with any other devices. 

### Device and Operating System

[Qtair7](https://www.devicespecifications.com/en/model/f4fe3805), Android 5.1

**Comment by yueyuzhao** [comment]
When I test on my android tablet, sometimes it will trigger the mouse event after the touch event, so I guest one possible reason is that these two events are triggered with one touch.

**Comment by deepankarmalhan** [comment]
Closing for now, will reopen if we get more reports.
