### ISSUE TITLE
Redesign sharing of projects to better handle normal and edge cases for all apps and rework

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#489]
### Expected Behavior

If you attempt to share by email on an iPad that does not have email configured, it should fail with a message to let you know that there are no email accounts available to share with.

This needs design, and it's perhaps unlikely on a personal iPad unless it's brand new. Related to #262 as we should probably re-think the whole share flow. 

### Actual Behavior

On an iPad that has never had email configured, select share by email. It does not open the email sharing dialog, and does not have any indication why.

### Device and Operating System

iPad mini 4

**Comment by deepankarmalhan** [comment]
Think about #262 when coming up with design architecture.

**Comment by deepankarmalhan** [comment]
Think about #181 for feature design.

**Comment by deepankarmalhan** [comment]
Product backlog
