### ISSUE TITLE
Refactor saveProject

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#493]
### Expected Behavior

it should be easy to understand what `saveProject` is doing{
https://github.com/LLK/scratchjr/blob/2a40e1724735d86ba7302aa21bfdb709a339a8a9/src/editor/ScratchJr.js#L352

### Suggestion
Before we supported story starters this method was probably much simpler.

To make it easier to understand don't try to handle everything in one condition.

Structure something more like:
```
if (Project.error || !changed) {
    // don't save, run callback if present, return
}
if (editable && mode==storyStarter) {
    if (storyStarted) {
        // save a new project
    } else {
        // storyStarter has changed in a way that doesn't trigger a save, just run any callback present
    }
}
if (editable && mode != storyStarter && changed) {
   // not a storyStarter, save current project
}
```

**Comment by deepankarmalhan** [comment]
SJR-162
