### ISSUE TITLE
Soft keyboard hides too quickly

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#494]
### Expected Behavior
Soft keyboard should stay open until done typing

### Actual Behavior

It looks like a recent change for handling keyboards on chromebooks introduced a bug on Android tablets. When I try to add a text sprite or change then name of the project the soft keyboard appears, and then immediately hides again.

I ran `git bisect` and it actually identified https://github.com/LLK/scratchjr/commit/29d6a92ee860d975fd24d7e3bdde302c19e0e3fb as the one where the keyboard problems started for my Samsung tablet. 

I bet that changing from `Activity` to `AppCompatActivity` in ScratchJrActivity introduced some new effects. We also changed versions of appcompat from 1.1.0 to 1.3.0, but I doubt that had as big an impact.
 
### Steps to Reproduce

Tap the ABC button to add a text sprite on an Android tablet

### Device and Operating System

Samsung SM-T280, 5.1.1

I was not able to reproduce on an Amazon Fire HD 8, so it may just be something messed up on my tablet.

**Comment by yueyuzhao** [comment]
I was unable to reproduce this on my android tablets or the 8 devices provided by online test service with android version 5.1.1 or 5.1.

**Comment by chrisgarrity** [comment]
It looks like it has something to do with the android top navigation bar, and the view resizing as the top bar shows/hides. I was able to use the keyboard with the following steps:
1. Touch yellow tab to get project info
2. Touch for parents and answer question
3. Touch share by email
4. Touch outside the share sheet to cancel the share, the top navigation will appear, while it's still visible tap in the title input
5. Top navigation stays visible, along with keyboard, able to change the title about 25% of the time.

It's still not clear whether this is an issue on any device other than my particular Samsung tablet.
