### ISSUE TITLE
Renaming characters should not copy the name from a different character

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#503]
### Expected Behavior

If a user clicks in the name of the character, deletes all the text, and then exits the input (either by hitting enter, closing the soft keyboard, or clicking the checkmark to exit paint editor), the name should:

- preferably remain blank (if this doesn't cause issues elsewhere)
- default to the name "character" (localized)

### Actual Behavior

The character ends up with the same name as the last character in the list.

### Steps to Reproduce

1. Add a character like the chicken
2. Add a character, and go into the paint editor
3. Click the name, and delete the text (also draw something)
4. Click the check mark to save the character
5. New character appears with the name "chicken" (or whatever character was previously added)

### Device and Operating System

Android: Samsung Galaxy Tab A (2019?)

**Comment by deepankarmalhan** [comment]
SJR-161
