### ISSUE TITLE
Can't add reshape points to sharp triangle upper right border in the paint editor

### ISSUE THREAD

**Issue by yueyuzhao** [LLK/scratchjr#504]
### Expected Behavior

Should add points where the mouse is up

### Actual Behavior

The paint editor add a point to the upper left border

### Steps to Reproduce

1. open the painter to create a new sprite
2. select the `triangle` shape tool
3. draw a sharp triangle, the angle of top corner is less than 30 degree, the sharper the better
4. change to the `select` mode
5. click the upper right border near the top to add a reshape point

### Device and Operating System

This can be reproduced on Android, iOS and macOS

**Comment by BryceLTaylor** [comment]
This may be the same, or at least related to, https://github.com/LLK/scratchjr/issues/465

**Comment by deepankarmalhan** [comment]
SJR-160
