### ISSUE TITLE
Flashing of 'About' content when switching between reference tabs

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#505]
### Expected Behavior

When you switch between reference tabs (About, Interface, Paint, Blocks) the content should load in a way that is not distracting.

### Actual Behavior

When switching to the "About ScratchJr" tab the list of Kickstarter supporters appears briefly before being replaced with the content.

I am guessing that the reason is that the text is translated, and the kickstarter list isn't. So the kickstarter list loads immediately with the page, and the rest of the content that comes before the list is inserted after looking up the correct translations.

### Steps to Reproduce

1. Tap the book icon to load the reference section
2. Switch to one of the guides
3. Switch back to the About tab (lower left)

### Device and Operating System

iPad and Android tablets.

**Comment by deepankarmalhan** [comment]
SJR-159
