### ISSUE TITLE
Character freezes when changing move block to a negative number while running 

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#509]
### Expected Behavior

Character should not freeze. Even if it needs to stop execution, you should be able to drag the character.

### Actual Behavior

If you have a move block inside a repeat loop, you can tap on the number to change the value while it's running. If you change the number to a positive number everything is fine. As soon as you type a minus '-', the character freezes. You cannot drag the character (you can return to the lobby and re-enter the project). If the grid is turned on, the highlighted indices become 'NaN' when you type '-'

Also, the character is missing from the thumbnail when you return to the lobby

### Steps to Reproduce

1. Add a move right block, and connect a repeat-forever (red category)
2. Turn the grid on
2. tap the strip to start it running, the character starts moving to the right
3. change the number to a different positive number, everything keeps moving
4. try to change the number to a negative number, everything stops as soon as the '-' is touched, highlighted grid values are 'NaN'

### Device and Operating System

confirmed on both iOS and Android

**Comment by yueyuzhao** [comment]
From Chris:

> One of the design principles of Scratch and ScratchJr is that users should be able to tinker with things while they're running to see the effect. It's been a bug in ScratchJr for ~7 years, and we haven't heard about it previously. So I think I'd rather schedule this as follow-up to figure out how to handle it without stopping all scripts.

**Comment by deepankarmalhan** [comment]
Created SJR-158
