### ISSUE TITLE
Without an Android email app on a Chromebook you can't share with email

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratchjr#538]
### Expected Behavior

Sharing a project via email should have options for applications to use.

### Actual Behavior

The Share by email option won't present any apps to choose from unless you have an ANDROID email application installed.  This is true even on a chromebook that will have a chromebook email app available. 

This is related to https://github.com/LLK/scratchjr/issues/489 

### Steps to Reproduce

Create a project in Scratch Jr. on a Chromebook that doesn't have an installed Android version of gmail (or similar mail app)
Go through the share by email
Note: no applications appear in the list of email applications

### System Details
ChromeOS

**Comment by deepankarmalhan** [comment]
Related to #547 and will be fixed in that issue.
