### ISSUE TITLE
Dragging a shape in the paint editor moves the shape above it as well.

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratchjr#539]
### Expected Behavior

Dragging a shape in the paint editor should just move that shape.

### Actual Behavior

When you drag a shape it moves the shape and whatever is above it.  That makes it extremely difficult to position shapes you have drawn. 

![Screenshot_20211206-155340_ScratchJr](https://user-images.githubusercontent.com/1088291/144921218-6786fb17-ef54-48de-92a8-e1ab9ea08aaf.jpg)

It only happens when they are a certain amount overlapped.  That amount is hard to quantify, but it's something like 1/3 to 1/2 overlapped.

### Steps to Reproduce

Create a new backdrop or sprite (works with both) and paint a new one. 
Choose the Square tool
Draw a square
Change colors and use the paint bucket too to fill it in
Draw a second square of a different color
Select the arrow tool
Overlap the two shapes about half way in any direction
Drag the bottom shape 
Note: the top shape comes with it

### System Details
Android Tablet running Android v. 11

**Comment by yueyuzhao** [comment]
This seems running as designed:

https://github.com/LLK/scratchjr/blob/1ac10441baae86e3a7f486522861d4fc34c7b57e/src/painteditor/PaintAction.js#L24-L27

**Comment by deepankarmalhan** [comment]
Intended behavior.
