### ISSUE TITLE
Can't drag the sun sprite if filled with a photo

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratchjr#540]
### Expected Behavior

All sprites can be dragged on the stage.

### Actual Behavior

If you edit the Sun sprite with a photo it will not be draggable on the stage.  You can't drag it by the part you filled with a photo, but you can drag it by the parts that aren't filled with a photo.

### Steps to Reproduce

Add the Sun sprite to a project
Edit the sprite (click the paintbrush)
Select the photo tool
Tap the center of the sun (You can fill a different part, but it's easiest to see if you choose the center)
Take a picture
Click the check box to leave the paint editor
Try to drag the sun
Note: You can't drag it unless you touch the edge of the sprite (the part without the photo)

### System Details
Android Tablet with Android v. 11
Also seen bo @seotts on a Chromebook

**Comment by yueyuzhao** [comment]
The app can only handle SVG sprites with `path` tags, the center part of the Sun sprite is a `circle`, change it to `path` will solve this.

**Comment by deepankarmalhan** [comment]
Created SJR-157
