### ISSUE TITLE
I'd like to be able to reshape the sprites

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratchjr#541]
### Expected Behavior

I'd like to be able to reshape the sprites, especially the people.  

### Actual Behavior

Currently with the arrow tool in the paint editor you can't really reshape the sprites that come in the library.  You can move them around, but you can't get points/handles to reshape them.

**Comment by yueyuzhao** [comment]
For now most of the people sprites SVG files are wrapped with a `g` element which prevents the body parts from reshaping.

**Comment by deepankarmalhan** [comment]
Intended behavior for now, but will revisit in future to see if it should be implemented in SJRW and SJRA.
