### ISSUE TITLE
ScratchJr icon is no longer getting included in the email when sharing a project

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#59]
This may be related to the problems with some tablets not knowing that ScratchJr should be associated with the sjr extension.

![img_0017](https://cloud.githubusercontent.com/assets/399209/14711416/42b8922c-07a7-11e6-94f2-1bdc4e44c3ad.PNG)

The attachment used to have the ScratchJr icon instead of plain white box. Definitely happens on iOS, would need to confirm on android.

**Comment by deepankarmalhan** [comment]
Closing for #489
