### ISSUE TITLE
Performance - uploading a project to ScratchJr from email doesn't immediately appear in My Projects even if the upload was successful

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratchjr#60]
If you upload a project to ScratchJr from an email, at first it doesn't show up in the My Projects list, but if you wait a few seconds or you go to another project or create a new project and then return to the My Projects list, the project will be there (works, scripts are there, etc.).

Steps to repro:
- On an iPad (I used Bacon)
- Open ScratchJr
- Open Gmail (it should be set to the lifelongkindergartenipad gmail account)
- Open an email from Chris Garrity entitled "Fwd: An error occurred with project..."
- Scroll to the bottom of the email and click on the attached project file
- It will ask you to choose what App you want to use to open it, choose "Copy to Scratch Jr"
- The ScratchJr landing page should load, blue background with the cat and two icons on it
- Click on the home icon
- You would expect to see the project corresponding to the project file from the email, but note its absence initially
- Click on a project and then the home icon to return to My Projects OR wait for a few seconds
- Note that the project you downloaded is now there. The project appears with a blue ribbon around it to signify it is a "new gift". 

You can repeat the above steps, but with ScratchJr closed initially (and let it get opened automatically when you choose the "Copy to ScratchJr" app), and the new project should show up almost immediately/ immediately once Scratch loads and you click on the Home icon. So, this seems to be a performance issue when the ScratchJr app is already running when you download the file from the email.

**Comment by chrisgarrity** [comment]
Now that we've moved import to native code import is faster. Closing this issue. We can reopen if we start getting new reports of projects not showing up fast enough.
