### ISSUE TITLE
Transition ScratchJr-iOS to use WKWebview

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#8]
_From @tmickel on February 3, 2016 16:58_

Currently we're using UIWebview. WKWebview is supported on iOS 8+, which according to our analytics is at least 80% of iOS users. Switching to WKWebview will provide better performance, a much nicer JS-native interface, and hopefully less bugs.

_Copied from original issue: LLK/scratchjr-private#466_

**Comment by yueyuzhao** [comment]
With ```WKWebView``` we can't get a return value directly from native which differs from Android.

**Comment by chrisgarrity** [comment]
Fixed in https://github.com/LLK/scratchjr/pull/291
