### ISSUE TITLE
Create UI automation tests to make testing easier

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#81]
Some possible frameworks:
- Calabash: http://calaba.sh/
- UIAutomator: https://developer.android.com/tools/testing-support-library/index.html#UIAutomator
- Espresso: https://developer.android.com/tools/testing-support-library/index.html#Espresso

Then we can run on "Amazon Device Farm" or a similar service Google is starting up soon.

Note this can work for iOS as well, in some of these frameworks.

---

Moved from LLK/scratchjr-private#255
/cc @markroth8

**Comment by deepankarmalhan** [comment]
We are using Jest with React Testing Library in rework, will keep this in mind for apps
